    g = {
    "nodes":  [
     {
       "id": 1,
       "name": "Carla Aparecida Arena Ventura",
       "color": "$green",
       "race": "branca",
       "state": "SP",
       "region": "Sudeste",
       "size": 9,
       "member": "no",
       "degrees": 16,
       "type": "estadual",
       "ranking": 592
     },
     {
       "id": 2,
       "name": "Rosana Aparecida Baeninger",
       "color": "$green",
       "race": "branca",
       "state": "SP",
       "region": "Sudeste",
       "size": 3,
       "member": "no",
       "degrees": 5,
       "type": "estadual",
       "ranking": 449
     },
     {
       "id": 3,
       "name": "Mariângela Spotti Lopes Fujita",
       "color": "$green",
       "race": "branca",
       "state": "SP",
       "region": "Sudeste",
       "size": 9,
       "member": "no",
       "degrees": 73,
       "type": "estadual",
       "ranking": 392
     },
     {
       "id": 4,
       "name": "Leilah Santiago Bufrem",
       "color": "$green",
       "race": "branca",
       "state": "PE",
       "region": "Nordeste",
       "size": 13,
       "member": "no",
       "degrees": 40,
       "type": "estadual",
       "ranking": 367
     },
     {
       "id": 5,
       "name": "Maria do Perpétuo Socorro Rodrigues Chaves",
       "color": "$green",
       "race": "parda",
       "state": "AM",
       "region": "Norte",
       "size": 0,
       "member": "no",
       "degrees": 37,
       "type": "estadual",
       "ranking": 349
     },
     {
       "id": 6,
       "name": "Cicilia Maria Krohling Peruzzo",
       "color": "$green",
       "race": "branca",
       "state": "SP",
       "region": "Sudeste",
       "size": 1,
       "member": "no",
       "degrees": 19,
       "type": "estadual",
       "ranking": 301
     },
     {
       "id": 7,
       "name": "Marta Lígia Pomim Valentim",
       "color": "$green",
       "race": "branca",
       "state": "SP",
       "region": "Sudeste",
       "size": 12,
       "member": "no",
       "degrees": 28,
       "type": "estadual",
       "ranking": 300
     },
     {
       "id": 8,
       "name": "Tania Casado",
       "color": "$green",
       "race": "branca",
       "state": "SP",
       "region": "Sudeste",
       "size": 0,
       "member": "no",
       "degrees": 38,
       "type": "estadual",
       "ranking": 297
     },
     {
       "id": 9,
       "name": "Giselda Maria Fernandes Novaes Hironaka",
       "color": "$green",
       "race": "branca",
       "state": "SP",
       "region": "Sudeste",
       "size": 4,
       "member": "no",
       "degrees": 15,
       "type": "estadual",
       "ranking": 286
     },
     {
       "id": 10,
       "name": "Sueli Mara Soares Pinto Ferreira",
       "color": "$green",
       "race": "branca",
       "state": "SP",
       "region": "Sudeste",
       "size": 1,
       "member": "no",
       "degrees": 11,
       "type": "estadual",
       "ranking": 285
     },
     {
       "id": 11,
       "name": "Silvana Aparecida Borsetti Gregorio Vidotti",
       "color": "$green",
       "race": "branca",
       "state": "SP",
       "region": "Sudeste",
       "size": 3,
       "member": "no",
       "degrees": 27,
       "type": "estadual",
       "ranking": 260
     },
     {
       "id": 12,
       "name": "Ada Pellegrini Grinover",
       "color": "$green",
       "race": "branca",
       "state": "SP",
       "region": "Sudeste",
       "size": 18,
       "member": "no",
       "degrees": 47,
       "type": "estadual",
       "ranking": 251
     },
     {
       "id": 13,
       "name": "Maria Sylvia Macchione Saes",
       "color": "$green",
       "race": "branca",
       "state": "SP",
       "region": "Sudeste",
       "size": 0,
       "member": "no",
       "degrees": 16,
       "type": "estadual",
       "ranking": 250
     },
     {
       "id": 14,
       "name": "Plácida Leopoldina Ventura Amorim da Costa Santos",
       "color": "$green",
       "race": "branca",
       "state": "SP",
       "region": "Sudeste",
       "size": 3,
       "member": "no",
       "degrees": 26,
       "type": "estadual",
       "ranking": 250
     },
     {
       "id": 15,
       "name": "Maria Aparecida Gouvêa",
       "color": "$green",
       "race": "branca",
       "state": "SP",
       "region": "Sudeste",
       "size": 1,
       "member": "no",
       "degrees": 87,
       "type": "estadual",
       "ranking": 246
     },
     {
       "id": 16,
       "name": "Larissa Liz Odreski Ramina",
       "color": "$green",
       "race": "branca",
       "state": "PR",
       "region": "Sul",
       "size": 5,
       "member": "no",
       "degrees": 8,
       "type": "estadual",
       "ranking": 233
     },
     {
       "id": 17,
       "name": "Maria Immacolata Vassallo de Lopes",
       "color": "$green",
       "race": "branca",
       "state": "SP",
       "region": "Sudeste",
       "size": 1,
       "member": "no",
       "degrees": 15,
       "type": "estadual",
       "ranking": 233
     },
     {
       "id": 18,
       "name": "Cláudia Souza Passador",
       "color": "$green",
       "race": "branca",
       "state": "SP",
       "region": "Sudeste",
       "size": 0,
       "member": "no",
       "degrees": 33,
       "type": "estadual",
       "ranking": 225
     },
     {
       "id": 19,
       "name": "Eliana Mendes de Souza Teixeira Roque",
       "color": "ciencias sociais aplicadas",
       "race": "parda",
       "state": "SP",
       "region": "Sudeste",
       "size": 10,
       "member": "no",
       "degrees": 8,
       "type": "estadual",
       "ranking": 205
     },
     {
       "id": 20,
       "name": "Silene de Moraes Freire",
       "color": "ciencias sociais aplicadas",
       "race": "parda",
       "state": "RJ",
       "region": "Sudeste",
       "size": 2,
       "member": "no",
       "degrees": 12,
       "type": "estadual",
       "ranking": 191
     },
     {
       "id": 21,
       "name": "Luisa Lina Villa",
       "color": red,
       "race": "branca",
       "state": "SP",
       "region": "Sudeste",
       "size": 29,
       "member": "sim",
       "degrees": 14,
       "type": "estadual",
       "ranking": 987
     },
     {
       "id": 22,
       "name": "Mayana Zatz",
       "color": red,
       "race": "branca",
       "state": "SP",
       "region": "Sudeste",
       "size": 56,
       "member": "sim",
       "degrees": 35,
       "type": "estadual",
       "ranking": 892
     },
     {
       "id": 23,
       "name": "Rita de Cassia Aleixo Tostes Passaglia",
       "color": red,
       "race": "branca",
       "state": "SP",
       "region": "Sudeste",
       "size": 12,
       "member": "sim",
       "degrees": 57,
       "type": "estadual",
       "ranking": 776
     },
     {
       "id": 24,
       "name": "Elaine Aparecida Del Bel Belluz Guimarães",
       "color": red,
       "race": "branca",
       "state": "SP",
       "region": "Sudeste",
       "size": 3,
       "member": "no",
       "degrees": 53,
       "type": "estadual",
       "ranking": 754
     },
     {
       "id": 25,
       "name": "Cláudia Lúcia de Moraes Forjaz",
       "color": red,
       "race": "branca",
       "state": "SP",
       "region": "Sudeste",
       "size": 2,
       "member": "no",
       "degrees": 51,
       "type": "estadual",
       "ranking": 730
     },
     {
       "id": 26,
       "name": "Leticia Veras Costa Lotufo",
       "color": red,
       "race": "branca",
       "state": "SP",
       "region": "Sudeste",
       "size": 2,
       "member": "no",
       "degrees": 5,
       "type": "estadual",
       "ranking": 721
     },
     {
       "id": 27,
       "name": "Lúcia Helena Faccioli",
       "color": red,
       "race": "branca",
       "state": "SP",
       "region": "Sudeste",
       "size": 6,
       "member": "no",
       "degrees": 28,
       "type": "estadual",
       "ranking": 693
     },
     {
       "id": 28,
       "name": "Janete Maria Cerutti",
       "color": red,
       "race": "branca",
       "state": "SP",
       "region": "Sudeste",
       "size": 8,
       "member": "no",
       "degrees": 100,
       "type": "estadual",
       "ranking": 662
     },
     {
       "id": 29,
       "name": "Maria Claudia Costa Irigoyen",
       "color": red,
       "race": "branca",
       "state": "SP",
       "region": "Sudeste",
       "size": 9,
       "member": "no",
       "degrees": 33,
       "type": "estadual",
       "ranking": 660
     },
     {
       "id": 30,
       "name": "Ohara Augusto",
       "color": red,
       "race": "branca",
       "state": "SP",
       "region": "Sudeste",
       "size": 32,
       "member": "sim",
       "degrees": 20,
       "type": "estadual",
       "ranking": 614
     },
     {
       "id": 31,
       "name": "Zuleica Bruno Fortes",
       "color": red,
       "race": "branca",
       "state": "SP",
       "region": "Sudeste",
       "size": 15,
       "member": "no",
       "degrees": 5,
       "type": "estadual",
       "ranking": 595
     },
     {
       "id": 32,
       "name": "Suely Vilela",
       "color": red,
       "race": "branca",
       "state": "SP",
       "region": "Sudeste",
       "size": 0,
       "member": "no",
       "degrees": 62,
       "type": "estadual",
       "ranking": 582
     },
     {
       "id": 33,
       "name": "Denise Vilarinho Tambourgi",
       "color": red,
       "race": "branca",
       "state": "SP",
       "region": "Sudeste",
       "size": 14,
       "member": "no",
       "degrees": 7,
       "type": "estadual",
       "ranking": 573
     },
     {
       "id": 34,
       "name": "Suely Kazue Nagahashi Marie",
       "color": red,
       "race": "branca",
       "state": "SP",
       "region": "Sudeste",
       "size": 2,
       "member": "no",
       "degrees": 8,
       "type": "estadual",
       "ranking": 556
     },
     {
       "id": 35,
       "name": "Marisa Helena Gennari de Medeiros",
       "color": red,
       "race": "branca",
       "state": "SP",
       "region": "Sudeste",
       "size": 30,
       "member": "no",
       "degrees": 4,
       "type": "estadual",
       "ranking": 554
     },
     {
       "id": 36,
       "name": "Fátima Ferreira-Briza",
       "color": red,
       "race": "branca",
       "state": "Salzburg",
       "region": "Exterior",
       "size": 5,
       "member": "no",
       "degrees": 11,
       "type": "estadual",
       "ranking": 551
     },
     {
       "id": 37,
       "name": "Shirley Schreier",
       "color": red,
       "race": "branca",
       "state": "SP",
       "region": "Sudeste",
       "size": 11,
       "member": "sim",
       "degrees": 14,
       "type": "estadual",
       "ranking": 544
     },
     {
       "id": 38,
       "name": "Sandra Helena Poliselli Farsky",
       "color": red,
       "race": "branca",
       "state": "SP",
       "region": "Sudeste",
       "size": 9,
       "member": "no",
       "degrees": 21,
       "type": "estadual",
       "ranking": 532
     },
     {
       "id": 39,
       "name": "Maria Rita dos Santos e Passos Bueno",
       "color": red,
       "race": "branca",
       "state": "SP",
       "region": "Sudeste",
       "size": 25,
       "member": "sim",
       "degrees": 6,
       "type": "estadual",
       "ranking": 505
     },
     {
       "id": 40,
       "name": "Rosa Maria Rodrigues Pereira",
       "color": "$blue",
       "race": "branca",
       "state": "SP",
       "region": "Sudeste",
       "size": 5,
       "member": "no",
       "degrees": 73,
       "type": "estadual",
       "ranking": 1079
     },
     {
       "id": 41,
       "name": "Berenice Bilharinho de Mendonça",
       "color": "$blue",
       "race": "branca",
       "state": "SP",
       "region": "Sudeste",
       "size": 10,
       "member": "sim",
       "degrees": 49,
       "type": "estadual",
       "ranking": 1021
     },
     {
       "id": 42,
       "name": "Deborah Carvalho Malta",
       "color": "$blue",
       "race": "branca",
       "state": "MG",
       "region": "Sudeste",
       "size": 54,
       "member": "no",
       "degrees": 3,
       "type": "estadual",
       "ranking": 1021
     },
     {
       "id": 43,
       "name": "Eloisa Silva Dutra de Oliveira Bonfá",
       "color": "$blue",
       "race": "branca",
       "state": "SP",
       "region": "Sudeste",
       "size": 7,
       "member": "no",
       "degrees": 45,
       "type": "estadual",
       "ranking": 932
     },
     {
       "id": 44,
       "name": "Maria Isabel Toulson Davisson Correia",
       "color": "$blue",
       "race": "branca",
       "state": "MG",
       "region": "Sudeste",
       "size": 18,
       "member": "no",
       "degrees": 46,
       "type": "estadual",
       "ranking": 930
     },
     {
       "id": 45,
       "name": "Isabela Judith Martins Bensenor",
       "color": "$blue",
       "race": "branca",
       "state": "SP",
       "region": "Sudeste",
       "size": 15,
       "member": "no",
       "degrees": 2,
       "type": "estadual",
       "ranking": 928
     },
     {
       "id": 46,
       "name": "Angelita Habr-Gama",
       "color": "$blue",
       "race": "branca",
       "state": "SP",
       "region": "Sudeste",
       "size": 19,
       "member": "no",
       "degrees": 120,
       "type": "estadual",
       "ranking": 902
     },
     {
       "id": 47,
       "name": "Amanda Guerra de Moraes Rego Sousa",
       "color": "$blue",
       "race": "branca",
       "state": "SP",
       "region": "Sudeste",
       "size": 0,
       "member": "no",
       "degrees": 158,
       "type": "estadual",
       "ranking": 892
     },
     {
       "id": 48,
       "name": "Alessandra Reis",
       "color": "$blue",
       "race": "branca",
       "state": "PR",
       "region": "Sul",
       "size": 30,
       "member": "no",
       "degrees": 15,
       "type": "estadual",
       "ranking": 826
     },
     {
       "id": 49,
       "name": "Josimeri Hebling Costa",
       "color": "$blue",
       "race": "branca",
       "state": "SP",
       "region": "Sudeste",
       "size": 16,
       "member": "no",
       "degrees": 120,
       "type": "estadual",
       "ranking": 824
     },
     {
       "id": 50,
       "name": "Marília Afonso Rabelo Buzalaf",
       "color": "$blue",
       "race": "branca",
       "state": "SP",
       "region": "Sudeste",
       "size": 9,
       "member": "no",
       "degrees": 69,
       "type": "estadual",
       "ranking": 823
     },
     {
       "id": 51,
       "name": "Vera Luiza Capelozzi",
       "color": "$blue",
       "race": "branca",
       "state": "SP",
       "region": "Sudeste",
       "size": 7,
       "member": "no",
       "degrees": 21,
       "type": "estadual",
       "ranking": 805
     },
     {
       "id": 52,
       "name": "Silvana Maria Quintana",
       "color": "$blue",
       "race": "branca",
       "state": "SP",
       "region": "Sudeste",
       "size": 0,
       "member": "no",
       "degrees": 32,
       "type": "estadual",
       "ranking": 795
     },
     {
       "id": 53,
       "name": "Telma Maria Braga Costa",
       "color": "$blue",
       "race": "branca",
       "state": "SP",
       "region": "Sudeste",
       "size": 0,
       "member": "no",
       "degrees": 59,
       "type": "estadual",
       "ranking": 779
     },
     {
       "id": 54,
       "name": "Rosely Sichieri",
       "color": "$blue",
       "race": "branca",
       "state": "RJ",
       "region": "Sudeste",
       "size": 35,
       "member": "no",
       "degrees": 12,
       "type": "estadual",
       "ranking": 760
     },
     {
       "id": 55,
       "name": "Vanda Jorgetti",
       "color": "$blue",
       "race": "branca",
       "state": "SP",
       "region": "Sudeste",
       "size": 8,
       "member": "no",
       "degrees": 15,
       "type": "estadual",
       "ranking": 749
     },
     {
       "id": 56,
       "name": "Patricia Chakur Brum",
       "color": "$blue",
       "race": "branca",
       "state": "SP",
       "region": "Sudeste",
       "size": 9,
       "member": "no",
       "degrees": 43,
       "type": "estadual",
       "ranking": 684
     },
     {
       "id": 57,
       "name": "Sandra Roberta Gouvea Ferreira Vivolo",
       "color": "$blue",
       "race": "parda",
       "state": "SP",
       "region": "Sudeste",
       "size": 19,
       "member": "no",
       "degrees": 7,
       "type": "estadual",
       "ranking": 683
     },
     {
       "id": 58,
       "name": "Joyce Maria Annichino-Bizzacchi",
       "color": "$blue",
       "race": "branca",
       "state": "SP",
       "region": "Sudeste",
       "size": 4,
       "member": "no",
       "degrees": 35,
       "type": "estadual",
       "ranking": 671
     },
     {
       "id": 59,
       "name": "Marcia Martins Marques",
       "color": "$blue",
       "race": "branca",
       "state": "SP",
       "region": "Sudeste",
       "size": 4,
       "member": "no",
       "degrees": 92,
       "type": "estadual",
       "ranking": 668
     },
     {
       "id": 60,
       "name": "Regina Guenka Palma Dibb",
       "color": "$blue",
       "race": "parda",
       "state": "SP",
       "region": "Sudeste",
       "size": 19,
       "member": "no",
       "degrees": 16,
       "type": "estadual",
       "ranking": 666
     },
     {
       "id": 61,
       "name": "Angela Maggio da Fonseca",
       "color": "$blue",
       "race": "parda",
       "state": "SP",
       "region": "Sudeste",
       "size": 12,
       "member": "no",
       "degrees": 26,
       "type": "estadual",
       "ranking": 619
     },
     {
       "id": 62,
       "name": "Marcia Caldas de Castro",
       "color": "$green",
       "race": "branca",
       "state": "Boston",
       "region": "Exterior",
       "size": 12,
       "member": "no",
       "degrees": 11,
       "type": "exterior",
       "ranking": 309
     },
     {
       "id": 63,
       "name": "Gabrielle Bezerra Sales",
       "color": "$green",
       "race": "branca",
       "state": "RS",
       "region": "Sul",
       "size": 4,
       "member": "no",
       "degrees": 3,
       "type": "exterior",
       "ranking": 299
     },
     {
       "id": 64,
       "name": "Elza Salvatori Berquó",
       "color": "$green",
       "race": "branca",
       "state": "SP",
       "region": "Sudeste",
       "size": 7,
       "member": "sim",
       "degrees": 16,
       "type": "exterior",
       "ranking": 289
     },
     {
       "id": 65,
       "name": "Maria Cláudia da Silva Antunes de Souza",
       "color": "$green",
       "race": "branca",
       "state": "SC",
       "region": "Sul",
       "size": 11,
       "member": "no",
       "degrees": 8,
       "type": "exterior",
       "ranking": 288
     },
     {
       "id": 66,
       "name": "Angela Maria Cavalcanti da Rocha",
       "color": "$green",
       "race": "branca",
       "state": "RJ",
       "region": "Sudeste",
       "size": 4,
       "member": "no",
       "degrees": 19,
       "type": "exterior",
       "ranking": 283
     },
     {
       "id": 67,
       "name": "Sandra Regina Martini",
       "color": "$green",
       "race": "branca",
       "state": "RS",
       "region": "Sul",
       "size": 7,
       "member": "no",
       "degrees": 2,
       "type": "exterior",
       "ranking": 278
     },
     {
       "id": 68,
       "name": "Beatriz Valadares Cendón",
       "color": "$green",
       "race": "branca",
       "state": "MG",
       "region": "Sudeste",
       "size": 10,
       "member": "no",
       "degrees": 37,
       "type": "exterior",
       "ranking": 268
     },
     {
       "id": 69,
       "name": "Marlei Pozzebon",
       "color": "$green",
       "race": "branca",
       "state": "SP",
       "region": "Sudeste",
       "size": 9,
       "member": "no",
       "degrees": 17,
       "type": "exterior",
       "ranking": 258
     },
     {
       "id": 70,
       "name": "Suzana Braga Rodrigues",
       "color": "$green",
       "race": "branca",
       "state": "MG",
       "region": "Sudeste",
       "size": 2,
       "member": "no",
       "degrees": 27,
       "type": "exterior",
       "ranking": 246
     },
     {
       "id": 71,
       "name": "Rosângela Angelin",
       "color": "$green",
       "race": "branca",
       "state": "RS",
       "region": "Sul",
       "size": 1,
       "member": "no",
       "degrees": 0,
       "type": "exterior",
       "ranking": 236
     },
     {
       "id": 72,
       "name": "Patrícia Krieger Grossi",
       "color": "$green",
       "race": "branca",
       "state": "RS",
       "region": "Sul",
       "size": 4,
       "member": "no",
       "degrees": 48,
       "type": "exterior",
       "ranking": 233
     },
     {
       "id": 73,
       "name": "Marinete Marins Povoa",
       "color": red,
       "race": "branca",
       "state": "PA",
       "region": "Norte",
       "size": 11,
       "member": "no",
       "degrees": 18,
       "type": "exterior",
       "ranking": 678
     },
     {
       "id": 74,
       "name": "Neusa Hamada",
       "color": red,
       "race": "parda",
       "state": "AM",
       "region": "Norte",
       "size": 19,
       "member": "no",
       "degrees": 11,
       "type": "exterior",
       "ranking": 667
     },
     {
       "id": 75,
       "name": "Leonor Gusmão",
       "color": red,
       "race": "branca",
       "state": "RJ",
       "region": "Sudeste",
       "size": 12,
       "member": "no",
       "degrees": 11,
       "type": "exterior",
       "ranking": 642
     },
     {
       "id": 76,
       "name": "Erna Geessien Kroon",
       "color": red,
       "race": "branca",
       "state": "MG",
       "region": "Sudeste",
       "size": 1,
       "member": "no",
       "degrees": 12,
       "type": "exterior",
       "ranking": 633
     },
     {
       "id": 77,
       "name": "Mariza de Andrade",
       "color": red,
       "race": "branca",
       "state": "Rochester",
       "region": "Exterior",
       "size": 16,
       "member": "no",
       "degrees": 25,
       "type": "exterior",
       "ranking": 614
     },
     {
       "id": 78,
       "name": "Luana Cassandra Breitenbach Barroso Coelho",
       "color": red,
       "race": "branca",
       "state": "PE",
       "region": "Nordeste",
       "size": 3,
       "member": "no",
       "degrees": 4,
       "type": "exterior",
       "ranking": 603
     },
     {
       "id": 79,
       "name": "Brenda Paula Figueiredo de Almeida Gomes",
       "color": "$blue",
       "race": "branca",
       "state": "SP",
       "region": "Sudeste",
       "size": 32,
       "member": "no",
       "degrees": 109,
       "type": "exterior",
       "ranking": 1256
     },
     {
       "id": 80,
       "name": "Irene de Lourdes Noronha",
       "color": "$blue",
       "race": "branca",
       "state": "SP",
       "region": "Sudeste",
       "size": 10,
       "member": "no",
       "degrees": 36,
       "type": "exterior",
       "ranking": 861
     },
     {
       "id": 81,
       "name": "Maria Inês Schmidt",
       "color": "$blue",
       "race": "branca",
       "state": "RS",
       "region": "Sul",
       "size": 27,
       "member": "sim",
       "degrees": 13,
       "type": "exterior",
       "ranking": 859
     },
     {
       "id": 82,
       "name": "Adriana Raffin Pohlmann",
       "color": "$blue",
       "race": "branca",
       "state": "RS",
       "region": "Sudeste",
       "size": 7,
       "member": "no",
       "degrees": 21,
       "type": "exterior",
       "ranking": 772
     },
     {
       "id": 83,
       "name": "Sílvia Stanisçuaski Guterres",
       "color": "$blue",
       "race": "branca",
       "state": "RS",
       "region": "Sudeste",
       "size": 6,
       "member": "no",
       "degrees": 6,
       "type": "exterior",
       "ranking": 765
     },
     {
       "id": 84,
       "name": "Maria das Graças Targino",
       "color": "$green",
       "race": "branca",
       "state": "PI",
       "region": "Nordeste",
       "size": 19,
       "member": "no",
       "degrees": 46,
       "type": "federal",
       "ranking": 337
     },
     {
       "id": 85,
       "name": "Marcia Carla Pereira Ribeiro",
       "color": "$green",
       "race": "branca",
       "state": "PR",
       "region": "Sul",
       "size": 13,
       "member": "no",
       "degrees": 31,
       "type": "federal",
       "ranking": 301
     },
     {
       "id": 86,
       "name": "Maria das Dores Saraiva de Loreto",
       "color": "$green",
       "race": "branca",
       "state": "MG",
       "region": "Sudeste",
       "size": 0,
       "member": "no",
       "degrees": 7,
       "type": "federal",
       "ranking": 264
     },
     {
       "id": 87,
       "name": "Betina Treiger Grupenmacher",
       "color": "$green",
       "race": "branca",
       "state": "PR",
       "region": "Sul",
       "size": 1,
       "member": "no",
       "degrees": 22,
       "type": "federal",
       "ranking": 240
     },
     {
       "id": 88,
       "name": "Renata Maria Abrantes Baracho Porto",
       "color": "$green",
       "race": "branca",
       "state": "MG",
       "region": "Sudeste",
       "size": 2,
       "member": "no",
       "degrees": 12,
       "type": "federal",
       "ranking": 240
     },
     {
       "id": 89,
       "name": "Maria Elizabeth Guimarães Teixeira Rocha",
       "color": "$green",
       "race": "branca",
       "state": "DF",
       "region": "Centro-Oeste",
       "size": 1,
       "member": "no",
       "degrees": 97,
       "type": "federal",
       "ranking": 229
     },
     {
       "id": 90,
       "name": "Celia Ribeiro Zaher",
       "color": "$green",
       "race": "branca",
       "state": "RJ",
       "region": "Sudeste",
       "size": 1,
       "member": "no",
       "degrees": 35,
       "type": "federal",
       "ranking": 228
     },
     {
       "id": 91,
       "name": "Ana Valéria Machado Mendonça",
       "color": "$green",
       "race": "branca",
       "state": "DF",
       "region": "Centro-Oeste",
       "size": 0,
       "member": "no",
       "degrees": 26,
       "type": "federal",
       "ranking": 223
     },
     {
       "id": 92,
       "name": "Patricia Rieken Macedo Rocco",
       "color": red,
       "race": "branca",
       "state": "RJ",
       "region": "Sudeste",
       "size": 5,
       "member": "sim",
       "degrees": 155,
       "type": "federal",
       "ranking": 1295
     },
     {
       "id": 93,
       "name": "Cristina Wayne Nogueira",
       "color": red,
       "race": "parda",
       "state": "RS",
       "region": "Sul",
       "size": 14,
       "member": "no",
       "degrees": 4,
       "type": "federal",
       "ranking": 1284
     },
     {
       "id": 94,
       "name": "Monica Levy Andersen",
       "color": red,
       "race": "branca",
       "state": "SP",
       "region": "Sudeste",
       "size": 54,
       "member": "no",
       "degrees": 60,
       "type": "federal",
       "ranking": 1200
     },
     {
       "id": 95,
       "name": "Angela Terezinha de Souza Wyse",
       "color": red,
       "race": "branca",
       "state": "RS",
       "region": "Sul",
       "size": 19,
       "member": "sim",
       "degrees": 27,
       "type": "federal",
       "ranking": 1120
     },
     {
       "id": 96,
       "name": "Helena Bonciani Nader",
       "color": red,
       "race": "branca",
       "state": "SP",
       "region": "Sudeste",
       "size": 19,
       "member": "sim",
       "degrees": 47,
       "type": "federal",
       "ranking": 885
     },
     {
       "id": 97,
       "name": "Maria Rosa Chitolina",
       "color": red,
       "race": "branca",
       "state": "RS",
       "region": "Sul",
       "size": 5,
       "member": "no",
       "degrees": 7,
       "type": "federal",
       "ranking": 758
     },
     {
       "id": 98,
       "name": "Aldina Maria Prado Barral",
       "color": red,
       "race": "branca",
       "state": "BA",
       "region": "Nordeste",
       "size": 19,
       "member": "sim",
       "degrees": 7,
       "type": "federal",
       "ranking": 745
     },
     {
       "id": 99,
       "name": "Patricia Torres Bozza Viola",
       "color": red,
       "race": "branca",
       "state": "RJ",
       "region": "Sudeste",
       "size": 11,
       "member": "no",
       "degrees": 9,
       "type": "federal",
       "ranking": 728
     },
     {
       "id": 100,
       "name": "Ana Lúcia Severo Rodrigues",
       "color": red,
       "race": "parda",
       "state": "SC",
       "region": "Sul",
       "size": 3,
       "member": "no",
       "degrees": 13,
       "type": "federal",
       "ranking": 721
     },
     {
       "id": 101,
       "name": "Claudia do Ó Pessoa",
       "color": red,
       "race": "branca",
       "state": "CE",
       "region": "Nordeste",
       "size": 4,
       "member": "no",
       "degrees": 9,
       "type": "federal",
       "ranking": 686
     },
     {
       "id": 102,
       "name": "Denise Maria Guimarães Freire",
       "color": red,
       "race": "branca",
       "state": "RJ",
       "region": "Sudeste",
       "size": 8,
       "member": "no",
       "degrees": 34,
       "type": "federal",
       "ranking": 686
     },
     {
       "id": 103,
       "name": "Kátia De Angelis",
       "color": red,
       "race": "branca",
       "state": "SP",
       "region": "Sudeste",
       "size": 7,
       "member": "no",
       "degrees": 96,
       "type": "federal",
       "ranking": 678
     },
     {
       "id": 104,
       "name": "Milena Botelho Pereira Soares",
       "color": red,
       "race": "branca",
       "state": "BA",
       "region": "Nordeste",
       "size": 13,
       "member": "no",
       "degrees": 12,
       "type": "federal",
       "ranking": 671
     },
     {
       "id": 105,
       "name": "Patrícia Cristina Lisbôa da Silva",
       "color": red,
       "race": "branca",
       "state": "RJ",
       "region": "Sudeste",
       "size": 5,
       "member": "no",
       "degrees": 55,
       "type": "federal",
       "ranking": 660
     },
     {
       "id": 106,
       "name": "Patricia Machado Rodrigues e Silva Martins",
       "color": red,
       "race": "branca",
       "state": "RJ",
       "region": "Sudeste",
       "size": 5,
       "member": "no",
       "degrees": 59,
       "type": "federal",
       "ranking": 647
     },
     {
       "id": 107,
       "name": "Maria Aparecida Juliano",
       "color": red,
       "race": "branca",
       "state": "SP",
       "region": "Sudeste",
       "size": 1,
       "member": "no",
       "degrees": 1,
       "type": "federal",
       "ranking": 639
     },
     {
       "id": 108,
       "name": "Carla Denise Bonan",
       "color": red,
       "race": "branca",
       "state": "RS",
       "region": "Sul",
       "size": 4,
       "member": "no",
       "degrees": 10,
       "type": "federal",
       "ranking": 592
     },
     {
       "id": 109,
       "name": "Célia Maria de Almeida Soares",
       "color": red,
       "race": "parda",
       "state": "GO",
       "region": "Centro-Oeste",
       "size": 7,
       "member": "no",
       "degrees": 23,
       "type": "federal",
       "ranking": 590
     },
     {
       "id": 110,
       "name": "Vera Maria Melchiors Morsch",
       "color": red,
       "race": "branca",
       "state": "RS",
       "region": "Sul",
       "size": 0,
       "member": "no",
       "degrees": 1,
       "type": "federal",
       "ranking": 556
     },
     {
       "id": 111,
       "name": "Ana Tereza Ribeiro de Vasconcelos",
       "color": red,
       "race": "branca",
       "state": "RJ",
       "region": "Sudeste",
       "size": 5,
       "member": "no",
       "degrees": 2,
       "type": "federal",
       "ranking": 548
     },
     {
       "id": 112,
       "name": "Ana Maria Oliveira Battastini",
       "color": red,
       "race": "branca",
       "state": "RS",
       "region": "Sul",
       "size": 2,
       "member": "no",
       "degrees": 12,
       "type": "federal",
       "ranking": 539
     },
     {
       "id": 113,
       "name": "Maria Martha Campos",
       "color": red,
       "race": "branca",
       "state": "RS",
       "region": "Sul",
       "size": 10,
       "member": "no",
       "degrees": 9,
       "type": "federal",
       "ranking": 530
     },
     {
       "id": 114,
       "name": "Gerly Anne de Castro Brito",
       "color": red,
       "race": "branca",
       "state": "CE",
       "region": "Nordeste",
       "size": 7,
       "member": "no",
       "degrees": 33,
       "type": "federal",
       "ranking": 527
     },
     {
       "id": 115,
       "name": "Juliana da Silva",
       "color": red,
       "race": "branca",
       "state": "RS",
       "region": "Sul",
       "size": 9,
       "member": "no",
       "degrees": 29,
       "type": "federal",
       "ranking": 518
     },
     {
       "id": 116,
       "name": "Helena Carla Castro",
       "color": red,
       "race": "preta",
       "state": "RJ",
       "region": "Sudeste",
       "size": 10,
       "member": "no",
       "degrees": 23,
       "type": "federal",
       "ranking": 440
     },
     {
       "id": 117,
       "name": "Ana Maria Baptista Menezes",
       "color": "$blue",
       "race": "branca",
       "state": "RS",
       "region": "Sul",
       "size": 48,
       "member": "no",
       "degrees": 30,
       "type": "federal",
       "ranking": 1297
     },
     {
       "id": 118,
       "name": "Lydia Masako Ferreira",
       "color": "$blue",
       "race": "branca",
       "state": "SP",
       "region": "Sudeste",
       "size": 1,
       "member": "no",
       "degrees": 167,
       "type": "federal",
       "ranking": 1114
     },
     {
       "id": 119,
       "name": "Sheila Knupp Feitosa de Oliveira",
       "color": "$blue",
       "race": "branca",
       "state": "RJ",
       "region": "Sudeste",
       "size": 55,
       "member": "no",
       "degrees": 15,
       "type": "federal",
       "ranking": 1103
     },
     {
       "id": 120,
       "name": "Ruth Guinsburg",
       "color": "$blue",
       "race": "branca",
       "state": "SP",
       "region": "Sudeste",
       "size": 11,
       "member": "no",
       "degrees": 66,
       "type": "federal",
       "ranking": 1035
     },
     {
       "id": 121,
       "name": "Laura Sterian Ward",
       "color": "$blue",
       "race": "branca",
       "state": "SP",
       "region": "Sudeste",
       "size": 6,
       "member": "no",
       "degrees": 74,
       "type": "federal",
       "ranking": 985
     },
     {
       "id": 122,
       "name": "Beatriz Gilda Jegerhorn Grinsztejn",
       "color": "$blue",
       "race": "branca",
       "state": "RJ",
       "region": "Sudeste",
       "size": 10,
       "member": "no",
       "degrees": 8,
       "type": "federal",
       "ranking": 978
     },
     {
       "id": 123,
       "name": "Iná da Silva dos Santos",
       "color": "$blue",
       "race": "branca",
       "state": "RS",
       "region": "Sul",
       "size": 38,
       "member": "no",
       "degrees": 10,
       "type": "federal",
       "ranking": 936
     },
     {
       "id": 124,
       "name": "Dulciene Maria de Magalhães Queiroz",
       "color": "$blue",
       "race": "branca",
       "state": "MG",
       "region": "Sudeste",
       "size": 56,
       "member": "sim",
       "degrees": 113,
       "type": "federal",
       "ranking": 922
     },
     {
       "id": 125,
       "name": "Maria Fernanda Furtado de Lima e Costa",
       "color": "$blue",
       "race": "branca",
       "state": "MG",
       "region": "Sudeste",
       "size": 59,
       "member": "no",
       "degrees": 17,
       "type": "federal",
       "ranking": 921
     },
     {
       "id": 126,
       "name": "Luciene Barbosa de Sousa",
       "color": "$blue",
       "race": "branca",
       "state": "SP",
       "region": "Sudeste",
       "size": 0,
       "member": "no",
       "degrees": 32,
       "type": "federal",
       "ranking": 837
     },
     {
       "id": 127,
       "name": "Maria Cristina de Oliveira Izar",
       "color": "$blue",
       "race": "branca",
       "state": "SP",
       "region": "Sudeste",
       "size": 1,
       "member": "no",
       "degrees": 42,
       "type": "federal",
       "ranking": 753
     },
     {
       "id": 128,
       "name": "Denise Petrucci Gigante",
       "color": "$blue",
       "race": "branca",
       "state": "RS",
       "region": "Sul",
       "size": 15,
       "member": "no",
       "degrees": 8,
       "type": "federal",
       "ranking": 726
     },
     {
       "id": 129,
       "name": "Ida Vanessa Doederlein Schwartz",
       "color": "$blue",
       "race": "branca",
       "state": "RS",
       "region": "Sul",
       "size": 3,
       "member": "no",
       "degrees": 36,
       "type": "federal",
       "ranking": 702
     },
     {
       "id": 130,
       "name": "Vera Lucia Szejnfeld",
       "color": "$blue",
       "race": "branca",
       "state": "SP",
       "region": "Sudeste",
       "size": 8,
       "member": "no",
       "degrees": 4,
       "type": "federal",
       "ranking": 701
     },
     {
       "id": 131,
       "name": "Sandra Cristina Pereira Costa Fuchs",
       "color": "$blue",
       "race": "branca",
       "state": "RS",
       "region": "Sul",
       "size": 21,
       "member": "no",
       "degrees": 14,
       "type": "federal",
       "ranking": 691
     },
     {
       "id": 132,
       "name": "Mara Suzana Behlau",
       "color": "$blue",
       "race": "branca",
       "state": "SP",
       "region": "Sudeste",
       "size": 0,
       "member": "no",
       "degrees": 131,
       "type": "federal",
       "ranking": 690
     },
     {
       "id": 133,
       "name": "Maria Cecilia de Souza Minayo",
       "color": "$blue",
       "race": "branca",
       "state": "RJ",
       "region": "Sudeste",
       "size": 71,
       "member": "no",
       "degrees": 37,
       "type": "federal",
       "ranking": 676
     },
     {
       "id": 134,
       "name": "Luciana Rodrigues Silva",
       "color": "$blue",
       "race": "branca",
       "state": "BA",
       "region": "Nordeste",
       "size": 0,
       "member": "no",
       "degrees": 48,
       "type": "federal",
       "ranking": 673
     },
     {
       "id": 135,
       "name": "Ana Cristina Gales",
       "color": "$blue",
       "race": "branca",
       "state": "SP",
       "region": "Sudeste",
       "size": 21,
       "member": "no",
       "degrees": 6,
       "type": "federal",
       "ranking": 671
     },
     {
       "id": 136,
       "name": "Marilia Sa Carvalho",
       "color": "$blue",
       "race": "branca",
       "state": "RJ",
       "region": "Sudeste",
       "size": 44,
       "member": "no",
       "degrees": 9,
       "type": "federal",
       "ranking": 661
     },
     {
       "id": 137,
       "name": "Euzenir Nunes Sarno",
       "color": "$blue",
       "race": "parda",
       "state": "RJ",
       "region": "Sudeste",
       "size": 4,
       "member": "no",
       "degrees": 12,
       "type": "federal",
       "ranking": 599
     },
     {
       "id": 138,
       "name": "Cristina Maria Garcia de Lima Parada",
       "color": "$blue",
       "race": "preta",
       "state": "SP",
       "region": "Sudeste",
       "size": 6,
       "member": "no",
       "degrees": 32,
       "type": "federal",
       "ranking": 312
     },
     {
       "id": 139,
       "name": "Viviane Coelho de Sellos-Knoerr",
       "color": "$green",
       "race": "branca",
       "state": "PR",
       "region": "Sul",
       "size": 11,
       "member": "no",
       "degrees": 52,
       "type": "privada",
       "ranking": 486
     },
     {
       "id": 140,
       "name": "Maria Ines Souza Bravo",
       "color": "$green",
       "race": "branca",
       "state": "RJ",
       "region": "Sudeste",
       "size": 9,
       "member": "no",
       "degrees": 39,
       "type": "privada",
       "ranking": 358
     },
     {
       "id": 141,
       "name": "Maria Beatriz Costa Abramides",
       "color": "$green",
       "race": "branca",
       "state": "SP",
       "region": "Sudeste",
       "size": 11,
       "member": "no",
       "degrees": 25,
       "type": "privada",
       "ranking": 326
     },
     {
       "id": 142,
       "name": "Maria de Fátima Ribeiro",
       "color": "$green",
       "race": "branca",
       "state": "PR",
       "region": "Sul",
       "size": 2,
       "member": "no",
       "degrees": 17,
       "type": "privada",
       "ranking": 301
     },
     {
       "id": 143,
       "name": "Vania Siciliano Aieta",
       "color": "$green",
       "race": "branca",
       "state": "RJ",
       "region": "Sudeste",
       "size": 1,
       "member": "no",
       "degrees": 60,
       "type": "privada",
       "ranking": 295
     },
     {
       "id": 144,
       "name": "Silvana Maria Escorsim",
       "color": "$green",
       "race": "branca",
       "state": "PR",
       "region": "Sul",
       "size": 1,
       "member": "no",
       "degrees": 6,
       "type": "privada",
       "ranking": 259
     },
     {
       "id": 145,
       "name": "Aldaiza Sposati",
       "color": "$green",
       "race": "branca",
       "state": "SP",
       "region": "Sudeste",
       "size": 25,
       "member": "no",
       "degrees": 13,
       "type": "privada",
       "ranking": 258
     },
     {
       "id": 146,
       "name": "Maria Liduína de Oliveira e Silva",
       "color": "$green",
       "race": "parda",
       "state": "SP",
       "region": "Sudeste",
       "size": 13,
       "member": "no",
       "degrees": 6,
       "type": "privada",
       "ranking": 243
     },
     {
       "id": 147,
       "name": "Mara Vidigal Darcanchy",
       "color": "$green",
       "race": "branca",
       "state": "PR",
       "region": "Sul",
       "size": 2,
       "member": "no",
       "degrees": 34,
       "type": "privada",
       "ranking": 240
     },
     {
       "id": 148,
       "name": "Thaise Nara Graziottin Costa",
       "color": "$green",
       "race": "branca",
       "state": "RS",
       "region": "Sul",
       "size": 3,
       "member": "no",
       "degrees": 15,
       "type": "privada",
       "ranking": 233
     },
     {
       "id": 149,
       "name": "Maria Aparecida Moura",
       "color": "ciencias sociais aplicadas",
       "race": "preta",
       "state": "MG",
       "region": "Sudeste",
       "size": 9,
       "member": "no",
       "degrees": 25,
       "type": "privada",
       "ranking": 197
     },
     {
       "id": 150,
       "name": "Patrícia Maria de Moraes Barros Fucs",
       "color": "$blue",
       "race": "branca",
       "state": "SP",
       "region": "Sudeste",
       "size": 0,
       "member": "no",
       "degrees": 89,
       "type": "privada",
       "ranking": 891
     },
     {
       "id": 151,
       "name": "Maria Elena Pol",
       "color": "$yellow",
       "race": "branca",
       "state": "RJ",
       "region": "Sudeste",
       "size": 0,
       "member": "no",
       "degrees": 0,
       "type": "privada",
       "ranking": 4306
     },
     {
       "id": 152,
       "name": "Carmen Lucia Lodi Maidantchik",
       "color": "$yellow",
       "race": "na",
       "state": "",
       "region": "",
       "size": 6,
       "member": "no",
       "degrees": 4,
       "type": "",
       "ranking": 2386
     },
     {
       "id": 153,
       "name": "Marcia Begalli",
       "color": "$yellow",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 6,
       "member": "no",
       "degrees": 1,
       "type": "",
       "ranking": 2370
     },
     {
       "id": 154,
       "name": "Sandra dos Santos Padula",
       "color": "$yellow",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 2,
       "member": "no",
       "degrees": 0,
       "type": "",
       "ranking": 2353
     },
     {
       "id": 155,
       "name": "Marisilvia Donadelli",
       "color": "$yellow",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 19,
       "member": "no",
       "degrees": 0,
       "type": "",
       "ranking": 2202
     },
     {
       "id": 156,
       "name": "Carla Gobel Burlamaqui de Mello",
       "color": "$yellow",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 83,
       "member": "no",
       "degrees": 4,
       "type": "",
       "ranking": 2110
     },
     {
       "id": 157,
       "name": "Eliza Melo da Costa",
       "color": "$yellow",
       "race": "parda",
       "state": "",
       "region": "",
       "size": 11,
       "member": "no",
       "degrees": 0,
       "type": "",
       "ranking": 1948
     },
     {
       "id": 158,
       "name": "Sandra Filippa Amato",
       "color": "$yellow",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 80,
       "member": "no",
       "degrees": 1,
       "type": "",
       "ranking": 1859
     },
     {
       "id": 159,
       "name": "Miriam Mendes Gandelman",
       "color": "$yellow",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 88,
       "member": "no",
       "degrees": 0,
       "type": "",
       "ranking": 1765
     },
     {
       "id": 160,
       "name": "Analu Verçosa Custódio",
       "color": "$yellow",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 5,
       "member": "no",
       "degrees": 0,
       "type": "",
       "ranking": 1740
     },
     {
       "id": 161,
       "name": "Maria Clemencia Rosario Mora Herrera",
       "color": "$yellow",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 0,
       "member": "no",
       "degrees": 3,
       "type": "",
       "ranking": 1698
     },
     {
       "id": 162,
       "name": "Erica Ribeiro Polycarpo Macedo",
       "color": "$yellow",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 30,
       "member": "no",
       "degrees": 2,
       "type": "",
       "ranking": 1388
     },
     {
       "id": 163,
       "name": "Patricia Rebello Teles",
       "color": "$yellow",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 1,
       "member": "no",
       "degrees": 0,
       "type": "",
       "ranking": 1374
     },
     {
       "id": 164,
       "name": "Irina Nasteva",
       "color": "$yellow",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 1,
       "member": "no",
       "degrees": 4,
       "type": "",
       "ranking": 1053
     },
     {
       "id": 165,
       "name": "Wanda Lucia Prado da Silva",
       "color": "$yellow",
       "race": "na",
       "state": "",
       "region": "",
       "size": 1,
       "member": "no",
       "degrees": 0,
       "type": "",
       "ranking": 1051
     },
     {
       "id": 166,
       "name": "Jussara Marques de Miranda",
       "color": "$yellow",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 56,
       "member": "no",
       "degrees": 0,
       "type": "",
       "ranking": 970
     },
     {
       "id": 167,
       "name": "Maria Valnice Boldrin",
       "color": "$yellow",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 34,
       "member": "no",
       "degrees": 25,
       "type": "",
       "ranking": 962
     },
     {
       "id": 168,
       "name": "Yara do Amaral Coutinho",
       "color": "$yellow",
       "race": "na",
       "state": "",
       "region": "",
       "size": 63,
       "member": "no",
       "degrees": 0,
       "type": "",
       "ranking": 921
     },
     {
       "id": 169,
       "name": "Sandra Helena Pulcinelli",
       "color": "$yellow",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 3,
       "member": "no",
       "degrees": 12,
       "type": "",
       "ranking": 816
     },
     {
       "id": 170,
       "name": "Susana Ines Cordoba de Torresi",
       "color": "$yellow",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 82,
       "member": "sim",
       "degrees": 18,
       "type": "",
       "ranking": 754
     },
     {
       "id": 171,
       "name": "Emi Marcia Takagui",
       "color": "$yellow",
       "race": "na",
       "state": "",
       "region": "",
       "size": 9,
       "member": "no",
       "degrees": 0,
       "type": "",
       "ranking": 741
     },
     {
       "id": 172,
       "name": "Maria Fatima das Gracas Fernandes da Silva",
       "color": "$yellow",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 41,
       "member": "no",
       "degrees": 8,
       "type": "",
       "ranking": 731
     },
     {
       "id": 173,
       "name": "Marilia Oliveira Fonseca Goulart",
       "color": "$yellow",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 47,
       "member": "sim",
       "degrees": 34,
       "type": "",
       "ranking": 724
     },
     {
       "id": 174,
       "name": "Marcia Laudelina Arruda Temperini",
       "color": "$yellow",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 63,
       "member": "no",
       "degrees": 3,
       "type": "",
       "ranking": 710
     },
     {
       "id": 175,
       "name": "Flavia de Almeida Dias",
       "color": "$yellow",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 0,
       "member": "no",
       "degrees": 0,
       "type": "",
       "ranking": 692
     },
     {
       "id": 176,
       "name": "Inez Staciarini Batista",
       "color": "$yellow",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 11,
       "member": "no",
       "degrees": 2,
       "type": "",
       "ranking": 692
     },
     {
       "id": 177,
       "name": "Marcia Cristina Bernardes Barbosa",
       "color": "$yellow",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 16,
       "member": "sim",
       "degrees": 6,
       "type": "",
       "ranking": 679
     },
     {
       "id": 178,
       "name": "Elisa Maria Baggio Saitovitch",
       "color": "$yellow",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 55,
       "member": "no",
       "degrees": 2,
       "type": "",
       "ranking": 665
     },
     {
       "id": 179,
       "name": "Teresa Dib Zambon Atvars",
       "color": "$yellow",
       "race": "parda",
       "state": "",
       "region": "",
       "size": 59,
       "member": "no",
       "degrees": 17,
       "type": "",
       "ranking": 647
     },
     {
       "id": 180,
       "name": "Suzana Pereira Nunes",
       "color": "$yellow",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 13,
       "member": "no",
       "degrees": 1,
       "type": "",
       "ranking": 643
     },
     {
       "id": 181,
       "name": "Thaisa Storchi Bergmann",
       "color": "$yellow",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 55,
       "member": "sim",
       "degrees": 9,
       "type": "",
       "ranking": 640
     },
     {
       "id": 182,
       "name": "Maria Beatriz de Leone Gay Ducati",
       "color": "$yellow",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 46,
       "member": "no",
       "degrees": 6,
       "type": "",
       "ranking": 629
     },
     {
       "id": 183,
       "name": "Renata Zukanovich Funchal",
       "color": "$yellow",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 71,
       "member": "no",
       "degrees": 0,
       "type": "",
       "ranking": 628
     },
     {
       "id": 184,
       "name": "Denise Freitas Siqueira Petri",
       "color": "$yellow",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 15,
       "member": "no",
       "degrees": 10,
       "type": "",
       "ranking": 626
     },
     {
       "id": 185,
       "name": "Maria do Rosario Dias de Oliveira Latorre",
       "color": "$yellow",
       "race": "parda",
       "state": "",
       "region": "",
       "size": 1,
       "member": "no",
       "degrees": 19,
       "type": "",
       "ranking": 618
     },
     {
       "id": 186,
       "name": "Danielle Magalhães Moraes",
       "color": "$yellow",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 112,
       "member": "no",
       "degrees": 2,
       "type": "",
       "ranking": 608
     },
     {
       "id": 187,
       "name": "Magdalena Malek",
       "color": "$yellow",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 0,
       "member": "no",
       "degrees": 0,
       "type": "",
       "ranking": 608
     },
     {
       "id": 188,
       "name": "Maysa Furlan",
       "color": "$yellow",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 14,
       "member": "sim",
       "degrees": 22,
       "type": "",
       "ranking": 606
     },
     {
       "id": 189,
       "name": "Sheila Mara Silva do Amaral",
       "color": "$yellow",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 0,
       "member": "no",
       "degrees": 0,
       "type": "",
       "ranking": 601
     },
     {
       "id": 190,
       "name": "Ana Paula Baptista de Carvalho",
       "color": "$yellow",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 8,
       "member": "no",
       "degrees": 0,
       "type": "",
       "ranking": 588
     },
     {
       "id": 191,
       "name": "Debora Peres Menezes",
       "color": "$yellow",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 29,
       "member": "no",
       "degrees": 5,
       "type": "",
       "ranking": 586
     },
     {
       "id": 192,
       "name": "Galina Klimtchitskaia",
       "color": "$yellow",
       "race": "na",
       "state": "",
       "region": "",
       "size": 44,
       "member": "no",
       "degrees": 1,
       "type": "",
       "ranking": 575
     },
     {
       "id": 193,
       "name": "Teresa Bernarda Ludermir",
       "color": "$yellow",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 8,
       "member": "no",
       "degrees": 15,
       "type": "",
       "ranking": 574
     },
     {
       "id": 194,
       "name": "Maria Auxiliadora Coelho Kaplan",
       "color": "$yellow",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 9,
       "member": "sim",
       "degrees": 45,
       "type": "",
       "ranking": 557
     },
     {
       "id": 195,
       "name": "Gláucia Maria Bovi Ambrosano",
       "color": "$yellow",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 0,
       "member": "no",
       "degrees": 46,
       "type": "",
       "ranking": 555
     },
     {
       "id": 196,
       "name": "Quezia Bezerra Cass",
       "color": "$yellow",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 14,
       "member": "no",
       "degrees": 1,
       "type": "",
       "ranking": 554
     },
     {
       "id": 197,
       "name": "Marina Nielsen",
       "color": "$yellow",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 9,
       "member": "no",
       "degrees": 2,
       "type": "",
       "ranking": 553
     },
     {
       "id": 198,
       "name": "Denise Maria Zezell",
       "color": "$yellow",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 11,
       "member": "no",
       "degrees": 30,
       "type": "",
       "ranking": 550
     },
     {
       "id": 199,
       "name": "Maria Aline Barros do Vale",
       "color": "$yellow",
       "race": "parda",
       "state": "",
       "region": "",
       "size": 1,
       "member": "no",
       "degrees": 0,
       "type": "",
       "ranking": 509
     },
     {
       "id": 200,
       "name": "Danielle Martins Tostes",
       "color": "$yellow",
       "race": "preta",
       "state": "",
       "region": "",
       "size": 0,
       "member": "no",
       "degrees": 1,
       "type": "",
       "ranking": 541
     },
     {
       "id": 201,
       "name": "Bluma Guenther Soares",
       "color": "$purple",
       "race": "parda",
       "state": "",
       "region": "",
       "size": 68,
       "member": "no",
       "degrees": 4,
       "type": "",
       "ranking": 864
     },
     {
       "id": 202,
       "name": "Maria Ines Bruno Tavares",
       "color": "$purple",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 76,
       "member": "no",
       "degrees": 23,
       "type": "",
       "ranking": 858
     },
     {
       "id": 203,
       "name": "Maria Regina Wolf Maciel",
       "color": "$purple",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 28,
       "member": "no",
       "degrees": 11,
       "type": "",
       "ranking": 655
     },
     {
       "id": 204,
       "name": "Fernanda Margarida Barbosa Coutinho",
       "color": "$purple",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 46,
       "member": "no",
       "degrees": 6,
       "type": "",
       "ranking": 574
     },
     {
       "id": 205,
       "name": "Iêda Maria Garcia dos Santos",
       "color": "$purple",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 4,
       "member": "no",
       "degrees": 9,
       "type": "",
       "ranking": 571
     },
     {
       "id": 206,
       "name": "Dulce Maria de Araújo Melo",
       "color": "$purple",
       "race": "parda",
       "state": "",
       "region": "",
       "size": 34,
       "member": "no",
       "degrees": 5,
       "type": "",
       "ranking": 555
     },
     {
       "id": 207,
       "name": "Maria Aparecida Zaghete Bertochi",
       "color": "$purple",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 3,
       "member": "no",
       "degrees": 4,
       "type": "",
       "ranking": 553
     },
     {
       "id": 208,
       "name": "Selene Maria de Arruda Guelli Ulson de Souza",
       "color": "$purple",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 10,
       "member": "no",
       "degrees": 34,
       "type": "",
       "ranking": 537
     },
     {
       "id": 209,
       "name": "Raquel Santos Mauler",
       "color": "$purple",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 5,
       "member": "no",
       "degrees": 0,
       "type": "",
       "ranking": 491
     },
     {
       "id": 210,
       "name": "Marisa Masumi Beppu",
       "color": "$purple",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 10,
       "member": "no",
       "degrees": 35,
       "type": "",
       "ranking": 490
     },
     {
       "id": 211,
       "name": "Luciana Reyes Pires Kassab",
       "color": "$purple",
       "race": "parda",
       "state": "",
       "region": "",
       "size": 32,
       "member": "no",
       "degrees": 10,
       "type": "",
       "ranking": 465
     },
     {
       "id": 212,
       "name": "Ruth Herta Goldschmidt Aliaga Kiminami",
       "color": "$purple",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 1,
       "member": "no",
       "degrees": 12,
       "type": "",
       "ranking": 456
     },
     {
       "id": 213,
       "name": "Ducinei Garcia",
       "color": "$purple",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 2,
       "member": "no",
       "degrees": 19,
       "type": "",
       "ranking": 443
     },
     {
       "id": 214,
       "name": "Gisella Maria Zanin",
       "color": "$purple",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 7,
       "member": "no",
       "degrees": 25,
       "type": "",
       "ranking": 439
     },
     {
       "id": 215,
       "name": "Linda Viola Ehlin Caldas",
       "color": "$purple",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 4,
       "member": "no",
       "degrees": 1,
       "type": "",
       "ranking": 438
     },
     {
       "id": 216,
       "name": "Andrea Simone Stucchi de Camargo Alvarez Bernardez",
       "color": "$purple",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 17,
       "member": "no",
       "degrees": 7,
       "type": "",
       "ranking": 431
     },
     {
       "id": 217,
       "name": "Rosangela Bergamasco",
       "color": "$purple",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 6,
       "member": "no",
       "degrees": 9,
       "type": "",
       "ranking": 430
     },
     {
       "id": 218,
       "name": "Sofia Maria Carrato Diniz",
       "color": "$purple",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 4,
       "member": "no",
       "degrees": 75,
       "type": "",
       "ranking": 420
     },
     {
       "id": 219,
       "name": "Raquel de Lima Camargo Giordano",
       "color": "$purple",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 4,
       "member": "no",
       "degrees": 10,
       "type": "",
       "ranking": 419
     },
     {
       "id": 220,
       "name": "Judith Pessoa de Andrade Feitosa",
       "color": "$purple",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 10,
       "member": "no",
       "degrees": 3,
       "type": "",
       "ranking": 418
     },
     {
       "id": 221,
       "name": "Maria do Carmo Rangel Santos Varela",
       "color": "$purple",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 32,
       "member": "no",
       "degrees": 4,
       "type": "",
       "ranking": 416
     },
     {
       "id": 222,
       "name": "Andrea Moura Bernardes",
       "color": "$purple",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 8,
       "member": "no",
       "degrees": 18,
       "type": "",
       "ranking": 410
     },
     {
       "id": 223,
       "name": "Martha Simões Ribeiro",
       "color": "$purple",
       "race": "parda",
       "state": "",
       "region": "",
       "size": 3,
       "member": "no",
       "degrees": 29,
       "type": "",
       "ranking": 408
     },
     {
       "id": 224,
       "name": "Regina de Fátima Peralta Muniz Moreira",
       "color": "$purple",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 11,
       "member": "no",
       "degrees": 20,
       "type": "",
       "ranking": 400
     },
     {
       "id": 225,
       "name": "Diana Cristina Silva de Azevedo",
       "color": "$purple",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 8,
       "member": "no",
       "degrees": 4,
       "type": "",
       "ranking": 398
     },
     {
       "id": 226,
       "name": "Eliana Navarro dos Santos Muccillo",
       "color": "$purple",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 33,
       "member": "no",
       "degrees": 4,
       "type": "",
       "ranking": 398
     },
     {
       "id": 227,
       "name": "Claudia Sayer",
       "color": "$purple",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 6,
       "member": "no",
       "degrees": 3,
       "type": "",
       "ranking": 395
     },
     {
       "id": 228,
       "name": "Mirabel Cerqueira Rezende",
       "color": "$purple",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 16,
       "member": "no",
       "degrees": 10,
       "type": "",
       "ranking": 385
     },
     {
       "id": 229,
       "name": "Maria Bernadete Amâncio Varesche",
       "color": "$purple",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 0,
       "member": "no",
       "degrees": 11,
       "type": "",
       "ranking": 377
     },
     {
       "id": 230,
       "name": "Aimé Peláiz Barranco",
       "color": "$purple",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 22,
       "member": "no",
       "degrees": 53,
       "type": "",
       "ranking": 375
     },
     {
       "id": 231,
       "name": "Marcia Walquiria de Carvalho Dezotti",
       "color": "$purple",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 3,
       "member": "no",
       "degrees": 23,
       "type": "",
       "ranking": 373
     },
     {
       "id": 232,
       "name": "Elisabete Frollini",
       "color": "$purple",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 8,
       "member": "no",
       "degrees": 3,
       "type": "",
       "ranking": 367
     },
     {
       "id": 233,
       "name": "Maria Ines Basso Bernardi",
       "color": "$purple",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 32,
       "member": "no",
       "degrees": 7,
       "type": "",
       "ranking": 367
     },
     {
       "id": 234,
       "name": "Debora Terezia Balogh",
       "color": "$purple",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 5,
       "member": "no",
       "degrees": 0,
       "type": "",
       "ranking": 363
     },
     {
       "id": 235,
       "name": "Luciana Rocha Barros Gonçalves",
       "color": "$purple",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 7,
       "member": "no",
       "degrees": 6,
       "type": "",
       "ranking": 361
     },
     {
       "id": 236,
       "name": "Virginia Sampaio Teixeira Ciminelli",
       "color": "$purple",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 12,
       "member": "sim",
       "degrees": 25,
       "type": "",
       "ranking": 357
     },
     {
       "id": 237,
       "name": "Fernanda Roberta Marciano",
       "color": "$purple",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 14,
       "member": "no",
       "degrees": 9,
       "type": "",
       "ranking": 354
     },
     {
       "id": 238,
       "name": "Helen Jamil Khoury",
       "color": "$purple",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 7,
       "member": "no",
       "degrees": 12,
       "type": "",
       "ranking": 353
     },
     {
       "id": 239,
       "name": "Cleide Mara Faria Soares",
       "color": "$purple",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 11,
       "member": "no",
       "degrees": 0,
       "type": "",
       "ranking": 345
     },
     {
       "id": 240,
       "name": "Cheila Gonçalves Mothé",
       "color": "$purple",
       "race": "preta",
       "state": "",
       "region": "",
       "size": 37,
       "member": "no",
       "degrees": 22,
       "type": "",
       "ranking": 344
     },
     {
       "id": 241,
       "name": "Leda dos Reis Castilho",
       "color": "$purple",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 10,
       "member": "no",
       "degrees": 40,
       "type": "",
       "ranking": 330
     },
     {
       "id": 242,
       "name": "Sergiane Caldas Barbosa",
       "color": "$purple",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 10,
       "member": "no",
       "degrees": 11,
       "type": "",
       "ranking": 329
     },
     {
       "id": 243,
       "name": "Alexandra Ancelmo Piscitelli Mansur",
       "color": "$purple",
       "race": "na",
       "state": "",
       "region": "",
       "size": 18,
       "member": "no",
       "degrees": 4,
       "type": "",
       "ranking": 323
     },
     {
       "id": 244,
       "name": "Irenilza de Alencar Naas",
       "color": "$purple",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 2,
       "member": "no",
       "degrees": 39,
       "type": "",
       "ranking": 318
     },
     {
       "id": 245,
       "name": "Mariana de Mattos Vieira Mello Souza",
       "color": "$purple",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 9,
       "member": "no",
       "degrees": 12,
       "type": "",
       "ranking": 312
     },
     {
       "id": 246,
       "name": "Ana Paula da Luz",
       "color": "$purple",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 28,
       "member": "no",
       "degrees": 5,
       "type": "",
       "ranking": 309
     },
     {
       "id": 247,
       "name": "Ligia Damasceno Ferreira Marczak",
       "color": "$purple",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 0,
       "member": "no",
       "degrees": 34,
       "type": "",
       "ranking": 308
     },
     {
       "id": 248,
       "name": "Maria Helena Andrade Santana",
       "color": "$purple",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 7,
       "member": "no",
       "degrees": 8,
       "type": "",
       "ranking": 307
     },
     {
       "id": 249,
       "name": "Neyde Yukie Murakami Iha",
       "color": "$purple",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 12,
       "member": "no",
       "degrees": 12,
       "type": "",
       "ranking": 305
     },
     {
       "id": 250,
       "name": "Telma Teixeira Franco",
       "color": "$purple",
       "race": "branca",
       "state": "",
       "region": "",
       "size": 11,
       "member": "no",
       "degrees": 5,
       "type": "",
       "ranking": 305
     },
  ],
};
