pessoas = {
  "nodes":  [
   {
     "id": 1,
     "name": "Vera Maria Melchiors Morsch",
     "color": "rgba(224, 79, 46, 0.5)",
     "race": "branca",
     "state": "RS",
     "region": "Sul",
     "size": 0,
     "member": "no",
     "degrees": 1,
     "type": "federal",
     "ranking": 556
   },
   {
     "id": 2,
     "name": "Maria Aparecida Juliano",
     "color": "rgba(224, 79, 46, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 1,
     "member": "no",
     "degrees": 1,
     "type": "federal",
     "ranking": 639
   },
   {
     "id": 3,
     "name": "Ana Tereza Ribeiro de Vasconcelos",
     "color": "rgba(224, 79, 46, 0.5)",
     "race": "branca",
     "state": "RJ",
     "region": "Sudeste",
     "size": 5,
     "member": "no",
     "degrees": 2,
     "type": "federal",
     "ranking": 548
   },
   {
     "id": 4,
     "name": "Marisa Helena Gennari de Medeiros",
     "color": "rgba(224, 79, 46, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 30,
     "member": "no",
     "degrees": 4,
     "type": "estadual",
     "ranking": 554
   },
   {
     "id": 5,
     "name": "Luana Cassandra Breitenbach Barroso Coelho",
     "color": "rgba(224, 79, 46, 0.5)",
     "race": "branca",
     "state": "PE",
     "region": "Nordeste",
     "size": 3,
     "member": "no",
     "degrees": 4,
     "type": "exterior",
     "ranking": 603
   },
   {
     "id": 6,
     "name": "Cristina Wayne Nogueira",
     "color": "rgba(224, 79, 46, 0.5)",
     "race": "parda",
     "state": "RS",
     "region": "Sul",
     "size": 14,
     "member": "no",
     "degrees": 4,
     "type": "federal",
     "ranking": 1284
   },
   {
     "id": 7,
     "name": "Zuleica Bruno Fortes",
     "color": "rgba(224, 79, 46, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 15,
     "member": "no",
     "degrees": 5,
     "type": "estadual",
     "ranking": 595
   },
   {
     "id": 8,
     "name": "Leticia Veras Costa Lotufo",
     "color": "rgba(224, 79, 46, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 2,
     "member": "no",
     "degrees": 5,
     "type": "estadual",
     "ranking": 721
   },
   {
     "id": 9,
     "name": "Ester Cerdeira Sabino",
     "color": "rgba(224, 79, 46, 0.5)",
     "race": "parda",
     "state": "SP",
     "region": "Sudeste",
     "size": 9,
     "member": "no",
     "degrees": 2,
     "type": "estadual",
     "ranking": 460
   },
   {
     "id": 10,
     "name": "Denise Vilarinho Tambourgi",
     "color": "rgba(224, 79, 46, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 14,
     "member": "no",
     "degrees": 7,
     "type": "estadual",
     "ranking": 573
   },
   {
     "id": 11,
     "name": "Aldina Maria Prado Barral",
     "color": "rgba(224, 79, 46, 0.5)",
     "race": "branca",
     "state": "BA",
     "region": "Nordeste",
     "size": 19,
     "member": "yes",
     "degrees": 7,
     "type": "federal",
     "ranking": 745
   },
   {
     "id": 12,
     "name": "Maria Rosa Chitolina",
     "color": "rgba(224, 79, 46, 0.5)",
     "race": "branca",
     "state": "RS",
     "region": "Sul",
     "size": 5,
     "member": "no",
     "degrees": 7,
     "type": "federal",
     "ranking": 758
   },
   {
     "id": 13,
     "name": "Suely Kazue Nagahashi Marie",
     "color": "rgba(224, 79, 46, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 2,
     "member": "no",
     "degrees": 8,
     "type": "estadual",
     "ranking": 556
   },
   {
     "id": 14,
     "name": "Maria Martha Campos",
     "color": "rgba(224, 79, 46, 0.5)",
     "race": "branca",
     "state": "RS",
     "region": "Sul",
     "size": 10,
     "member": "no",
     "degrees": 9,
     "type": "federal",
     "ranking": 530
   },
   {
     "id": 15,
     "name": "Claudia do Ó Pessoa",
     "color": "rgba(224, 79, 46, 0.5)",
     "race": "branca",
     "state": "CE",
     "region": "Nordeste",
     "size": 4,
     "member": "no",
     "degrees": 9,
     "type": "federal",
     "ranking": 686
   },
   {
     "id": 16,
     "name": "Patricia Torres Bozza Viola",
     "color": "rgba(224, 79, 46, 0.5)",
     "race": "branca",
     "state": "RJ",
     "region": "Sudeste",
     "size": 11,
     "member": "no",
     "degrees": 9,
     "type": "federal",
     "ranking": 728
   },
   {
     "id": 17,
     "name": "Carla Denise Bonan",
     "color": "rgba(224, 79, 46, 0.5)",
     "race": "branca",
     "state": "RS",
     "region": "Sul",
     "size": 4,
     "member": "no",
     "degrees": 10,
     "type": "federal",
     "ranking": 592
   },
   {
     "id": 18,
     "name": "Fátima Ferreira-Briza",
     "color": "rgba(224, 79, 46, 0.5)",
     "race": "branca",
     "state": "Salzburg",
     "region": "Exterior",
     "size": 5,
     "member": "no",
     "degrees": 11,
     "type": "estadual",
     "ranking": 551
   },
   {
     "id": 19,
     "name": "Leonor Gusmão",
     "color": "rgba(224, 79, 46, 0.5)",
     "race": "branca",
     "state": "RJ",
     "region": "Sudeste",
     "size": 12,
     "member": "no",
     "degrees": 11,
     "type": "exterior",
     "ranking": 642
   },
   {
     "id": 20,
     "name": "Neusa Hamada",
     "color": "rgba(224, 79, 46, 0.5)",
     "race": "parda",
     "state": "AM",
     "region": "Norte",
     "size": 19,
     "member": "no",
     "degrees": 11,
     "type": "exterior",
     "ranking": 667
   },
   {
     "id": 21,
     "name": "Ana Maria Oliveira Battastini",
     "color": "rgba(224, 79, 46, 0.5)",
     "race": "branca",
     "state": "RS",
     "region": "Sul",
     "size": 2,
     "member": "no",
     "degrees": 12,
     "type": "federal",
     "ranking": 539
   },
   {
     "id": 22,
     "name": "Erna Geessien Kroon",
     "color": "rgba(224, 79, 46, 0.5)",
     "race": "branca",
     "state": "MG",
     "region": "Sudeste",
     "size": 1,
     "member": "no",
     "degrees": 12,
     "type": "exterior",
     "ranking": 633
   },
   {
     "id": 23,
     "name": "Milena Botelho Pereira Soares",
     "color": "rgba(224, 79, 46, 0.5)",
     "race": "branca",
     "state": "BA",
     "region": "Nordeste",
     "size": 13,
     "member": "no",
     "degrees": 12,
     "type": "federal",
     "ranking": 671
   },
   {
     "id": 24,
     "name": "Ana Lúcia Severo Rodrigues",
     "color": "rgba(224, 79, 46, 0.5)",
     "race": "parda",
     "state": "SC",
     "region": "Sul",
     "size": 3,
     "member": "no",
     "degrees": 13,
     "type": "federal",
     "ranking": 721
   },
   {
     "id": 25,
     "name": "Shirley Schreier",
     "color": "rgba(224, 79, 46, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 11,
     "member": "yes",
     "degrees": 14,
     "type": "estadual",
     "ranking": 544
   },
   {
     "id": 26,
     "name": "Luisa Lina Villa",
     "color": "rgba(224, 79, 46, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 29,
     "member": "yes",
     "degrees": 14,
     "type": "estadual",
     "ranking": 987
   },
   {
     "id": 27,
     "name": "Marinete Marins Povoa",
     "color": "rgba(224, 79, 46, 0.5)",
     "race": "branca",
     "state": "PA",
     "region": "Norte",
     "size": 11,
     "member": "no",
     "degrees": 18,
     "type": "exterior",
     "ranking": 678
   },
   {
     "id": 28,
     "name": "Ohara Augusto",
     "color": "rgba(224, 79, 46, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 32,
     "member": "yes",
     "degrees": 20,
     "type": "estadual",
     "ranking": 614
   },
   {
     "id": 29,
     "name": "Sandra Helena Poliselli Farsky",
     "color": "rgba(224, 79, 46, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 9,
     "member": "no",
     "degrees": 21,
     "type": "estadual",
     "ranking": 532
   },
   {
     "id": 30,
     "name": "Helena Carla Castro",
     "color": "rgba(224, 79, 46, 0.5)",
     "race": "preta",
     "state": "RJ",
     "region": "Sudeste",
     "size": 10,
     "member": "no",
     "degrees": 23,
     "type": "federal",
     "ranking": 440
   },
   {
     "id": 31,
     "name": "Célia Maria de Almeida Soares",
     "color": "rgba(224, 79, 46, 0.5)",
     "race": "parda",
     "state": "GO",
     "region": "Centro-Oeste",
     "size": 7,
     "member": "no",
     "degrees": 23,
     "type": "federal",
     "ranking": 590
   },
   {
     "id": 32,
     "name": "Mariza de Andrade",
     "color": "rgba(224, 79, 46, 0.5)",
     "race": "branca",
     "state": "Rochester",
     "region": "Exterior",
     "size": 16,
     "member": "no",
     "degrees": 25,
     "type": "exterior",
     "ranking": 614
   },
   {
     "id": 33,
     "name": "Angela Terezinha de Souza Wyse",
     "color": "rgba(224, 79, 46, 0.5)",
     "race": "branca",
     "state": "RS",
     "region": "Sul",
     "size": 19,
     "member": "yes",
     "degrees": 27,
     "type": "federal",
     "ranking": 1120
   },
   {
     "id": 34,
     "name": "Lúcia Helena Faccioli",
     "color": "rgba(224, 79, 46, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 6,
     "member": "no",
     "degrees": 28,
     "type": "estadual",
     "ranking": 693
   },
   {
     "id": 35,
     "name": "Juliana da Silva",
     "color": "rgba(224, 79, 46, 0.5)",
     "race": "branca",
     "state": "RS",
     "region": "Sul",
     "size": 9,
     "member": "no",
     "degrees": 29,
     "type": "federal",
     "ranking": 518
   },
   {
     "id": 36,
     "name": "Gerly Anne de Castro Brito",
     "color": "rgba(224, 79, 46, 0.5)",
     "race": "branca",
     "state": "CE",
     "region": "Nordeste",
     "size": 7,
     "member": "no",
     "degrees": 33,
     "type": "federal",
     "ranking": 527
   },
   {
     "id": 37,
     "name": "Maria Claudia Costa Irigoyen",
     "color": "rgba(224, 79, 46, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 9,
     "member": "no",
     "degrees": 33,
     "type": "estadual",
     "ranking": 660
   },
   {
     "id": 38,
     "name": "Denise Maria Guimarães Freire",
     "color": "rgba(224, 79, 46, 0.5)",
     "race": "branca",
     "state": "RJ",
     "region": "Sudeste",
     "size": 8,
     "member": "no",
     "degrees": 34,
     "type": "federal",
     "ranking": 686
   },
   {
     "id": 39,
     "name": "Mayana Zatz",
     "color": "rgba(224, 79, 46, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 56,
     "member": "yes",
     "degrees": 35,
     "type": "estadual",
     "ranking": 892
   },
   {
     "id": 40,
     "name": "Helena Bonciani Nader",
     "color": "rgba(224, 79, 46, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 19,
     "member": "yes",
     "degrees": 47,
     "type": "federal",
     "ranking": 885
   },
   {
     "id": 41,
     "name": "Cláudia Lúcia de Moraes Forjaz",
     "color": "rgba(224, 79, 46, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 2,
     "member": "no",
     "degrees": 51,
     "type": "estadual",
     "ranking": 730
   },
   {
     "id": 42,
     "name": "Elaine Aparecida Del Bel Belluz Guimarães",
     "color": "rgba(224, 79, 46, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 3,
     "member": "no",
     "degrees": 53,
     "type": "estadual",
     "ranking": 754
   },
   {
     "id": 43,
     "name": "Patrícia Cristina Lisbôa da Silva",
     "color": "rgba(224, 79, 46, 0.5)",
     "race": "branca",
     "state": "RJ",
     "region": "Sudeste",
     "size": 5,
     "member": "no",
     "degrees": 55,
     "type": "federal",
     "ranking": 660
   },
   {
     "id": 44,
     "name": "Rita de Cassia Aleixo Tostes Passaglia",
     "color": "rgba(224, 79, 46, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 12,
     "member": "yes",
     "degrees": 57,
     "type": "estadual",
     "ranking": 776
   },
   {
     "id": 45,
     "name": "Patricia Machado Rodrigues e Silva Martins",
     "color": "rgba(224, 79, 46, 0.5)",
     "race": "branca",
     "state": "RJ",
     "region": "Sudeste",
     "size": 5,
     "member": "no",
     "degrees": 59,
     "type": "federal",
     "ranking": 647
   },
   {
     "id": 46,
     "name": "Monica Levy Andersen",
     "color": "rgba(224, 79, 46, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 54,
     "member": "no",
     "degrees": 60,
     "type": "federal",
     "ranking": 1200
   },
   {
     "id": 47,
     "name": "Suely Vilela",
     "color": "rgba(224, 79, 46, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 0,
     "member": "no",
     "degrees": 62,
     "type": "estadual",
     "ranking": 582
   },
   {
     "id": 48,
     "name": "Kátia De Angelis",
     "color": "rgba(224, 79, 46, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 7,
     "member": "no",
     "degrees": 96,
     "type": "federal",
     "ranking": 678
   },
   {
     "id": 49,
     "name": "Janete Maria Cerutti",
     "color": "rgba(224, 79, 46, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 8,
     "member": "no",
     "degrees": 100,
     "type": "estadual",
     "ranking": 662
   },
   {
     "id": 50,
     "name": "Patricia Rieken Macedo Rocco",
     "color": "rgba(224, 79, 46, 0.5)",
     "race": "branca",
     "state": "RJ",
     "region": "Sudeste",
     "size": 5,
     "member": "yes",
     "degrees": 155,
     "type": "federal",
     "ranking": 1295
   },
   {
     "id": 51,
     "name": "Isabela Judith Martins Bensenor",
     "color": "rgba(38, 135, 252, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 15,
     "member": "no",
     "degrees": 2,
     "type": "estadual",
     "ranking": 928
   },
   {
     "id": 52,
     "name": "Deborah Carvalho Malta",
     "color": "rgba(38, 135, 252, 0.5)",
     "race": "branca",
     "state": "MG",
     "region": "Sudeste",
     "size": 54,
     "member": "no",
     "degrees": 3,
     "type": "estadual",
     "ranking": 1021
   },
   {
     "id": 53,
     "name": "Vera Lucia Szejnfeld",
     "color": "rgba(38, 135, 252, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 8,
     "member": "no",
     "degrees": 4,
     "type": "federal",
     "ranking": 701
   },
   {
     "id": 54,
     "name": "Ana Cristina Gales",
     "color": "rgba(38, 135, 252, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 21,
     "member": "no",
     "degrees": 6,
     "type": "federal",
     "ranking": 671
   },
   {
     "id": 55,
     "name": "Sílvia Stanisçuaski Guterres",
     "color": "rgba(38, 135, 252, 0.5)",
     "race": "branca",
     "state": "RS",
     "region": "Sudeste",
     "size": 6,
     "member": "no",
     "degrees": 6,
     "type": "exterior",
     "ranking": 765
   },
   {
     "id": 56,
     "name": "Sandra Roberta Gouvea Ferreira Vivolo",
     "color": "rgba(38, 135, 252, 0.5)",
     "race": "parda",
     "state": "SP",
     "region": "Sudeste",
     "size": 19,
     "member": "no",
     "degrees": 7,
     "type": "estadual",
     "ranking": 683
   },
   {
     "id": 57,
     "name": "Denise Petrucci Gigante",
     "color": "rgba(38, 135, 252, 0.5)",
     "race": "branca",
     "state": "RS",
     "region": "Sul",
     "size": 15,
     "member": "no",
     "degrees": 8,
     "type": "federal",
     "ranking": 726
   },
   {
     "id": 58,
     "name": "Beatriz Gilda Jegerhorn Grinsztejn",
     "color": "rgba(38, 135, 252, 0.5)",
     "race": "branca",
     "state": "RJ",
     "region": "Sudeste",
     "size": 10,
     "member": "no",
     "degrees": 8,
     "type": "federal",
     "ranking": 978
   },
   {
     "id": 59,
     "name": "Marilia Sa Carvalho",
     "color": "rgba(38, 135, 252, 0.5)",
     "race": "branca",
     "state": "RJ",
     "region": "Sudeste",
     "size": 44,
     "member": "no",
     "degrees": 9,
     "type": "federal",
     "ranking": 661
   },
   {
     "id": 60,
     "name": "Iná da Silva dos Santos",
     "color": "rgba(38, 135, 252, 0.5)",
     "race": "branca",
     "state": "RS",
     "region": "Sul",
     "size": 38,
     "member": "no",
     "degrees": 10,
     "type": "federal",
     "ranking": 936
   },
   {
     "id": 61,
     "name": "Euzenir Nunes Sarno",
     "color": "rgba(38, 135, 252, 0.5)",
     "race": "parda",
     "state": "RJ",
     "region": "Sudeste",
     "size": 4,
     "member": "no",
     "degrees": 12,
     "type": "federal",
     "ranking": 599
   },
   {
     "id": 62,
     "name": "Rosely Sichieri",
     "color": "rgba(38, 135, 252, 0.5)",
     "race": "branca",
     "state": "RJ",
     "region": "Sudeste",
     "size": 35,
     "member": "no",
     "degrees": 12,
     "type": "estadual",
     "ranking": 760
   },
   {
     "id": 63,
     "name": "Maria Inês Schmidt",
     "color": "rgba(38, 135, 252, 0.5)",
     "race": "branca",
     "state": "RS",
     "region": "Sul",
     "size": 27,
     "member": "yes",
     "degrees": 13,
     "type": "exterior",
     "ranking": 859
   },
   {
     "id": 64,
     "name": "Sandra Cristina Pereira Costa Fuchs",
     "color": "rgba(38, 135, 252, 0.5)",
     "race": "branca",
     "state": "RS",
     "region": "Sul",
     "size": 21,
     "member": "no",
     "degrees": 14,
     "type": "federal",
     "ranking": 691
   },
   {
     "id": 65,
     "name": "Vanda Jorgetti",
     "color": "rgba(38, 135, 252, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 8,
     "member": "no",
     "degrees": 15,
     "type": "estadual",
     "ranking": 749
   },
   {
     "id": 66,
     "name": "Alessandra Reis",
     "color": "rgba(38, 135, 252, 0.5)",
     "race": "branca",
     "state": "PR",
     "region": "Sul",
     "size": 30,
     "member": "no",
     "degrees": 15,
     "type": "estadual",
     "ranking": 826
   },
   {
     "id": 67,
     "name": "Sheila Knupp Feitosa de Oliveira",
     "color": "rgba(38, 135, 252, 0.5)",
     "race": "branca",
     "state": "RJ",
     "region": "Sudeste",
     "size": 55,
     "member": "no",
     "degrees": 15,
     "type": "federal",
     "ranking": 1103
   },
   {
     "id": 68,
     "name": "Regina Guenka Palma Dibb",
     "color": "rgba(38, 135, 252, 0.5)",
     "race": "parda",
     "state": "SP",
     "region": "Sudeste",
     "size": 19,
     "member": "no",
     "degrees": 16,
     "type": "estadual",
     "ranking": 666
   },
   {
     "id": 69,
     "name": "Maria Fernanda Furtado de Lima e Costa",
     "color": "rgba(38, 135, 252, 0.5)",
     "race": "branca",
     "state": "MG",
     "region": "Sudeste",
     "size": 59,
     "member": "no",
     "degrees": 17,
     "type": "federal",
     "ranking": 921
   },
   {
     "id": 70,
     "name": "Adriana Raffin Pohlmann",
     "color": "rgba(38, 135, 252, 0.5)",
     "race": "branca",
     "state": "RS",
     "region": "Sudeste",
     "size": 7,
     "member": "no",
     "degrees": 21,
     "type": "exterior",
     "ranking": 772
   },
   {
     "id": 71,
     "name": "Vera Luiza Capelozzi",
     "color": "rgba(38, 135, 252, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 7,
     "member": "no",
     "degrees": 21,
     "type": "estadual",
     "ranking": 805
   },
   {
     "id": 72,
     "name": "Angela Maggio da Fonseca",
     "color": "rgba(38, 135, 252, 0.5)",
     "race": "parda",
     "state": "SP",
     "region": "Sudeste",
     "size": 12,
     "member": "no",
     "degrees": 26,
     "type": "estadual",
     "ranking": 619
   },
   {
     "id": 73,
     "name": "Ana Maria Baptista Menezes",
     "color": "rgba(38, 135, 252, 0.5)",
     "race": "branca",
     "state": "RS",
     "region": "Sul",
     "size": 48,
     "member": "no",
     "degrees": 30,
     "type": "federal",
     "ranking": 1297
   },
   {
     "id": 74,
     "name": "Cristina Maria Garcia de Lima Parada",
     "color": "rgba(38, 135, 252, 0.5)",
     "race": "parda",
     "state": "SP",
     "region": "Sudeste",
     "size": 6,
     "member": "no",
     "degrees": 32,
     "type": "federal",
     "ranking": 312
   },
   {
     "id": 75,
     "name": "Silvana Maria Quintana",
     "color": "rgba(38, 135, 252, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 0,
     "member": "no",
     "degrees": 32,
     "type": "estadual",
     "ranking": 795
   },
   {
     "id": 76,
     "name": "Luciene Barbosa de Sousa",
     "color": "rgba(38, 135, 252, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 0,
     "member": "no",
     "degrees": 32,
     "type": "federal",
     "ranking": 837
   },
   {
     "id": 77,
     "name": "Joyce Maria Annichino-Bizzacchi",
     "color": "rgba(38, 135, 252, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 4,
     "member": "no",
     "degrees": 35,
     "type": "estadual",
     "ranking": 671
   },
   {
     "id": 78,
     "name": "Ida Vanessa Doederlein Schwartz",
     "color": "rgba(38, 135, 252, 0.5)",
     "race": "branca",
     "state": "RS",
     "region": "Sul",
     "size": 3,
     "member": "no",
     "degrees": 36,
     "type": "federal",
     "ranking": 702
   },
   {
     "id": 79,
     "name": "Irene de Lourdes Noronha",
     "color": "rgba(38, 135, 252, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 10,
     "member": "no",
     "degrees": 36,
     "type": "exterior",
     "ranking": 861
   },
   {
     "id": 80,
     "name": "Maria Cecilia de Souza Minayo",
     "color": "rgba(38, 135, 252, 0.5)",
     "race": "branca",
     "state": "RJ",
     "region": "Sudeste",
     "size": 71,
     "member": "no",
     "degrees": 37,
     "type": "federal",
     "ranking": 676
   },
   {
     "id": 81,
     "name": "Maria Cristina de Oliveira Izar",
     "color": "rgba(38, 135, 252, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 1,
     "member": "no",
     "degrees": 42,
     "type": "federal",
     "ranking": 753
   },
   {
     "id": 82,
     "name": "Patricia Chakur Brum",
     "color": "rgba(38, 135, 252, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 9,
     "member": "no",
     "degrees": 43,
     "type": "estadual",
     "ranking": 684
   },
   {
     "id": 83,
     "name": "Eloisa Silva Dutra de Oliveira Bonfá",
     "color": "rgba(38, 135, 252, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 7,
     "member": "no",
     "degrees": 45,
     "type": "estadual",
     "ranking": 932
   },
   {
     "id": 84,
     "name": "Maria Isabel Toulson Davisson Correia",
     "color": "rgba(38, 135, 252, 0.5)",
     "race": "branca",
     "state": "MG",
     "region": "Sudeste",
     "size": 18,
     "member": "no",
     "degrees": 46,
     "type": "estadual",
     "ranking": 930
   },
   {
     "id": 85,
     "name": "Luciana Rodrigues Silva",
     "color": "rgba(38, 135, 252, 0.5)",
     "race": "branca",
     "state": "BA",
     "region": "Nordeste",
     "size": 0,
     "member": "no",
     "degrees": 48,
     "type": "federal",
     "ranking": 673
   },
   {
     "id": 86,
     "name": "Berenice Bilharinho de Mendonça",
     "color": "rgba(38, 135, 252, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 10,
     "member": "yes",
     "degrees": 49,
     "type": "estadual",
     "ranking": 1021
   },
   {
     "id": 87,
     "name": "Telma Maria Braga Costa",
     "color": "rgba(38, 135, 252, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 0,
     "member": "no",
     "degrees": 59,
     "type": "estadual",
     "ranking": 779
   },
   {
     "id": 88,
     "name": "Ruth Guinsburg",
     "color": "rgba(38, 135, 252, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 11,
     "member": "no",
     "degrees": 66,
     "type": "federal",
     "ranking": 1035
   },
   {
     "id": 89,
     "name": "Marília Afonso Rabelo Buzalaf",
     "color": "rgba(38, 135, 252, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 9,
     "member": "no",
     "degrees": 69,
     "type": "estadual",
     "ranking": 823
   },
   {
     "id": 90,
     "name": "Rosa Maria Rodrigues Pereira",
     "color": "rgba(38, 135, 252, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 5,
     "member": "no",
     "degrees": 73,
     "type": "estadual",
     "ranking": 1079
   },
   {
     "id": 91,
     "name": "Laura Sterian Ward",
     "color": "rgba(38, 135, 252, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 6,
     "member": "no",
     "degrees": 74,
     "type": "federal",
     "ranking": 985
   },
   {
     "id": 92,
     "name": "Patrícia Maria de Moraes Barros Fucs",
     "color": "rgba(38, 135, 252, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 0,
     "member": "no",
     "degrees": 89,
     "type": "privada",
     "ranking": 891
   },
   {
     "id": 93,
     "name": "Marcia Martins Marques",
     "color": "rgba(38, 135, 252, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 4,
     "member": "no",
     "degrees": 92,
     "type": "estadual",
     "ranking": 668
   },
   {
     "id": 94,
     "name": "Brenda Paula Figueiredo de Almeida Gomes",
     "color": "rgba(38, 135, 252, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 32,
     "member": "no",
     "degrees": 109,
     "type": "exterior",
     "ranking": 1256
   },
   {
     "id": 95,
     "name": "Dulciene Maria de Magalhães Queiroz",
     "color": "rgba(38, 135, 252, 0.5)",
     "race": "branca",
     "state": "MG",
     "region": "Sudeste",
     "size": 56,
     "member": "yes",
     "degrees": 113,
     "type": "federal",
     "ranking": 922
   },
   {
     "id": 96,
     "name": "Josimeri Hebling Costa",
     "color": "rgba(38, 135, 252, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 16,
     "member": "no",
     "degrees": 120,
     "type": "estadual",
     "ranking": 824
   },
   {
     "id": 97,
     "name": "Angelita Habr-Gama",
     "color": "rgba(38, 135, 252, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 19,
     "member": "no",
     "degrees": 120,
     "type": "estadual",
     "ranking": 902
   },
   {
     "id": 98,
     "name": "Mara Suzana Behlau",
     "color": "rgba(38, 135, 252, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 0,
     "member": "no",
     "degrees": 131,
     "type": "federal",
     "ranking": 690
   },
   {
     "id": 99,
     "name": "Amanda Guerra de Moraes Rego Sousa",
     "color": "rgba(38, 135, 252, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 0,
     "member": "no",
     "degrees": 158,
     "type": "estadual",
     "ranking": 892
   },
   {
     "id": 100,
     "name": "Lydia Masako Ferreira",
     "color": "rgba(38, 135, 252, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 1,
     "member": "no",
     "degrees": 167,
     "type": "federal",
     "ranking": 1114
   },
   {
     "id": 101,
     "name": "Maria Elena Pol",
     "color": "rgba(245, 235, 53, 0.5)",
     "race": "branca",
     "state": "RJ",
     "region": "Sudeste",
     "size": 0,
     "member": "no",
     "degrees": 0,
     "type": "privada",
     "ranking": 4306
   },
   {
     "id": 102,
     "name": "Carmen Lucia Lodi Maidantchik",
     "color": "rgba(245, 235, 53, 0.5)",
     "race": "branca",
     "state": "RJ",
     "region": "Sudeste",
     "size": 6,
     "member": "no",
     "degrees": 4,
     "type": "federal",
     "ranking": 2386
   },
   {
     "id": 103,
     "name": "Marcia Begalli",
     "color": "rgba(245, 235, 53, 0.5)",
     "race": "branca",
     "state": "RJ",
     "region": "Sudeste",
     "size": 6,
     "member": "no",
     "degrees": 1,
     "type": "exterior",
     "ranking": 2370
   },
   {
     "id": 104,
     "name": "Sandra dos Santos Padula",
     "color": "rgba(245, 235, 53, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 2,
     "member": "no",
     "degrees": 0,
     "type": "estadual",
     "ranking": 2353
   },
   {
     "id": 105,
     "name": "Marisilvia Donadelli",
     "color": "rgba(245, 235, 53, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 19,
     "member": "no",
     "degrees": 0,
     "type": "estadual",
     "ranking": 2202
   },
   {
     "id": 106,
     "name": "Carla Gobel Burlamaqui de Mello",
     "color": "rgba(245, 235, 53, 0.5)",
     "race": "branca",
     "state": "RJ",
     "region": "Sudeste",
     "size": 83,
     "member": "no",
     "degrees": 4,
     "type": "federal",
     "ranking": 2110
   },
   {
     "id": 107,
     "name": "Eliza Melo da Costa",
     "color": "rgba(245, 235, 53, 0.5)",
     "race": "parda",
     "state": "RJ",
     "region": "Sudeste",
     "size": 11,
     "member": "no",
     "degrees": 0,
     "type": "estadual",
     "ranking": 1948
   },
   {
     "id": 108,
     "name": "Sandra Filippa Amato",
     "color": "rgba(245, 235, 53, 0.5)",
     "race": "branca",
     "state": "RJ",
     "region": "Sudeste",
     "size": 80,
     "member": "no",
     "degrees": 1,
     "type": "federal",
     "ranking": 1859
   },
   {
     "id": 109,
     "name": "Miriam Mendes Gandelman",
     "color": "rgba(245, 235, 53, 0.5)",
     "race": "branca",
     "state": "RJ",
     "region": "Sudeste",
     "size": 88,
     "member": "no",
     "degrees": 0,
     "type": "federal",
     "ranking": 1765
   },
   {
     "id": 110,
     "name": "Analu Verçosa Custódio",
     "color": "rgba(245, 235, 53, 0.5)",
     "race": "branca",
     "state": "RJ",
     "region": "Sudeste",
     "size": 5,
     "member": "no",
     "degrees": 0,
     "type": "estadual",
     "ranking": 1740
   },
   {
     "id": 111,
     "name": "Maria Clemencia Rosario Mora Herrera",
     "color": "rgba(245, 235, 53, 0.5)",
     "race": "branca",
     "state": "RJ",
     "region": "Sudeste",
     "size": 0,
     "member": "no",
     "degrees": 3,
     "type": "exterior",
     "ranking": 1698
   },
   {
     "id": 112,
     "name": "Erica Ribeiro Polycarpo Macedo",
     "color": "rgba(245, 235, 53, 0.5)",
     "race": "branca",
     "state": "RJ",
     "region": "Sudeste",
     "size": 30,
     "member": "no",
     "degrees": 2,
     "type": "federal",
     "ranking": 1388
   },
   {
     "id": 113,
     "name": "Patricia Rebello Teles",
     "color": "rgba(245, 235, 53, 0.5)",
     "race": "branca",
     "state": "RJ",
     "region": "Sudeste",
     "size": 1,
     "member": "no",
     "degrees": 0,
     "type": "federal",
     "ranking": 1374
   },
   {
     "id": 114,
     "name": "Irina Nasteva",
     "color": "rgba(245, 235, 53, 0.5)",
     "race": "branca",
     "state": "RJ",
     "region": "Sudeste",
     "size": 1,
     "member": "no",
     "degrees": 4,
     "type": "exterior",
     "ranking": 1053
   },
   {
     "id": 115,
     "name": "Wanda Lucia Prado da Silva",
     "color": "rgba(245, 235, 53, 0.5)",
     "race": "na",
     "state": "RJ",
     "region": "Sudeste",
     "size": 1,
     "member": "no",
     "degrees": 0,
     "type": "exterior",
     "ranking": 1051
   },
   {
     "id": 116,
     "name": "Jussara Marques de Miranda",
     "color": "rgba(245, 235, 53, 0.5)",
     "race": "branca",
     "state": "RJ",
     "region": "Sudeste",
     "size": 56,
     "member": "no",
     "degrees": 0,
     "type": "federal",
     "ranking": 970
   },
   {
     "id": 117,
     "name": "Maria Valnice Boldrin",
     "color": "rgba(245, 235, 53, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 34,
     "member": "no",
     "degrees": 25,
     "type": "estadual",
     "ranking": 962
   },
   {
     "id": 118,
     "name": "Yara do Amaral Coutinho",
     "color": "rgba(245, 235, 53, 0.5)",
     "race": "na",
     "state": "RJ",
     "region": "Sudeste",
     "size": 63,
     "member": "no",
     "degrees": 0,
     "type": "federal",
     "ranking": 921
   },
   {
     "id": 119,
     "name": "Sandra Helena Pulcinelli",
     "color": "rgba(245, 235, 53, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 3,
     "member": "no",
     "degrees": 12,
     "type": "estadual",
     "ranking": 816
   },
   {
     "id": 120,
     "name": "Susana Ines Cordoba de Torresi",
     "color": "rgba(245, 235, 53, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 82,
     "member": "yes",
     "degrees": 18,
     "type": "exterior",
     "ranking": 754
   },
   {
     "id": 121,
     "name": "Emi Marcia Takagui",
     "color": "rgba(245, 235, 53, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 9,
     "member": "no",
     "degrees": 0,
     "type": "estadual",
     "ranking": 741
   },
   {
     "id": 122,
     "name": "Maria Fatima das Gracas Fernandes da Silva",
     "color": "rgba(245, 235, 53, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 41,
     "member": "no",
     "degrees": 8,
     "type": "estadual",
     "ranking": 731
   },
   {
     "id": 123,
     "name": "Marilia Oliveira Fonseca Goulart",
     "color": "rgba(245, 235, 53, 0.5)",
     "race": "branca",
     "state": "AL",
     "region": "Nordeste",
     "size": 47,
     "member": "yes",
     "degrees": 34,
     "type": "federal",
     "ranking": 724
   },
   {
     "id": 124,
     "name": "Marcia Laudelina Arruda Temperini",
     "color": "rgba(245, 235, 53, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 63,
     "member": "no",
     "degrees": 3,
     "type": "estadual",
     "ranking": 710
   },
   {
     "id": 125,
     "name": "Flavia de Almeida Dias",
     "color": "rgba(245, 235, 53, 0.5)",
     "race": "branca",
     "state": "Edimburgo",
     "region": "Reino Unido",
     "size": 0,
     "member": "no",
     "degrees": 0,
     "type": "federal",
     "ranking": 692
   },
   {
     "id": 126,
     "name": "Inez Staciarini Batista",
     "color": "rgba(245, 235, 53, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 11,
     "member": "no",
     "degrees": 2,
     "type": "federal",
     "ranking": 692
   },
   {
     "id": 127,
     "name": "Marcia Cristina Bernardes Barbosa",
     "color": "rgba(245, 235, 53, 0.5)",
     "race": "branca",
     "state": "RS",
     "region": "Sul",
     "size": 16,
     "member": "yes",
     "degrees": 6,
     "type": "federal",
     "ranking": 679
   },
   {
     "id": 128,
     "name": "Elisa Maria Baggio Saitovitch",
     "color": "rgba(245, 235, 53, 0.5)",
     "race": "branca",
     "state": "RJ",
     "region": "Sudeste",
     "size": 55,
     "member": "no",
     "degrees": 2,
     "type": "federal",
     "ranking": 665
   },
   {
     "id": 129,
     "name": "Teresa Dib Zambon Atvars",
     "color": "rgba(245, 235, 53, 0.5)",
     "race": "parda",
     "state": "SP",
     "region": "Sudeste",
     "size": 59,
     "member": "no",
     "degrees": 17,
     "type": "estadual",
     "ranking": 647
   },
   {
     "id": 130,
     "name": "Suzana Pereira Nunes",
     "color": "rgba(245, 235, 53, 0.5)",
     "race": "branca",
     "state": "Thuwal",
     "region": "Arabia Saudita",
     "size": 13,
     "member": "no",
     "degrees": 1,
     "type": "estadual",
     "ranking": 643
   },
   {
     "id": 131,
     "name": "Thaisa Storchi Bergmann",
     "color": "rgba(245, 235, 53, 0.5)",
     "race": "branca",
     "state": "RS",
     "region": "Sul",
     "size": 55,
     "member": "yes",
     "degrees": 9,
     "type": "federal",
     "ranking": 640
   },
   {
     "id": 132,
     "name": "Maria Beatriz de Leone Gay Ducati",
     "color": "rgba(245, 235, 53, 0.5)",
     "race": "branca",
     "state": "RS",
     "region": "Sul",
     "size": 46,
     "member": "no",
     "degrees": 6,
     "type": "exterior",
     "ranking": 629
   },
   {
     "id": 133,
     "name": "Renata Zukanovich Funchal",
     "color": "rgba(245, 235, 53, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 71,
     "member": "no",
     "degrees": 0,
     "type": "exterior",
     "ranking": 628
   },
   {
     "id": 134,
     "name": "Denise Freitas Siqueira Petri",
     "color": "rgba(245, 235, 53, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 15,
     "member": "no",
     "degrees": 10,
     "type": "estadual",
     "ranking": 626
   },
   {
     "id": 135,
     "name": "Maria do Rosario Dias de Oliveira Latorre",
     "color": "rgba(245, 235, 53, 0.5)",
     "race": "parda",
     "state": "SP",
     "region": "Sudeste",
     "size": 1,
     "member": "no",
     "degrees": 19,
     "type": "estadual",
     "ranking": 618
   },
   {
     "id": 136,
     "name": "Magdalena Malek",
     "color": "rgba(245, 235, 53, 0.5)",
     "race": "branca",
     "state": "RJ",
     "region": "Sudeste",
     "size": 0,
     "member": "no",
     "degrees": 0,
     "type": "exterior",
     "ranking": 608
   },
   {
     "id": 137,
     "name": "Danielle Magalhães Moraes",
     "color": "rgba(245, 235, 53, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 112,
     "member": "no",
     "degrees": 2,
     "type": "federal",
     "ranking": 608
   },
   {
     "id": 138,
     "name": "Maysa Furlan",
     "color": "rgba(245, 235, 53, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 14,
     "member": "yes",
     "degrees": 22,
     "type": "estadual",
     "ranking": 606
   },
   {
     "id": 139,
     "name": "Sheila Mara Silva do Amaral",
     "color": "rgba(245, 235, 53, 0.5)",
     "race": "branca",
     "state": "RJ",
     "region": "Sudeste",
     "size": 0,
     "member": "no",
     "degrees": 0,
     "type": "estadual",
     "ranking": 601
   },
   {
     "id": 140,
     "name": "Ana Paula Baptista de Carvalho",
     "color": "rgba(245, 235, 53, 0.5)",
     "race": "branca",
     "state": "Lisboa",
     "region": "Portugal",
     "size": 8,
     "member": "no",
     "degrees": 0,
     "type": "exterior",
     "ranking": 588
   },
   {
     "id": 141,
     "name": "Debora Peres Menezes",
     "color": "rgba(245, 235, 53, 0.5)",
     "race": "branca",
     "state": "SC",
     "region": "Sul",
     "size": 29,
     "member": "no",
     "degrees": 5,
     "type": "exterior",
     "ranking": 586
   },
   {
     "id": 142,
     "name": "Anita Jocelyne Marsaioli",
     "color": "rgba(245, 235, 53, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 10,
     "member": "yes",
     "degrees": 8,
     "type": "estadual",
     "ranking": 543
   },
   {
     "id": 143,
     "name": "Teresa Bernarda Ludermir",
     "color": "rgba(245, 235, 53, 0.5)",
     "race": "branca",
     "state": "PE",
     "region": "Nordeste",
     "size": 8,
     "member": "no",
     "degrees": 15,
     "type": "exterior",
     "ranking": 574
   },
   {
     "id": 144,
     "name": "Maria Auxiliadora Coelho Kaplan",
     "color": "rgba(245, 235, 53, 0.5)",
     "race": "branca",
     "state": "RJ",
     "region": "Sudeste",
     "size": 9,
     "member": "yes",
     "degrees": 45,
     "type": "exterior",
     "ranking": 557
   },
   {
     "id": 145,
     "name": "Gláucia Maria Bovi Ambrosano",
     "color": "rgba(245, 235, 53, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 0,
     "member": "no",
     "degrees": 46,
     "type": "estadual",
     "ranking": 555
   },
   {
     "id": 146,
     "name": "Quezia Bezerra Cass",
     "color": "rgba(245, 235, 53, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 14,
     "member": "no",
     "degrees": 1,
     "type": "exterior",
     "ranking": 554
   },
   {
     "id": 147,
     "name": "Marina Nielsen",
     "color": "rgba(245, 235, 53, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 9,
     "member": "no",
     "degrees": 2,
     "type": "estadual",
     "ranking": 553
   },
   {
     "id": 148,
     "name": "Denise Maria Zezell",
     "color": "rgba(245, 235, 53, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 11,
     "member": "no",
     "degrees": 30,
     "type": "estadual",
     "ranking": 550
   },
   {
     "id": 149,
     "name": "Danielle Martins Tostes",
     "color": "rgba(245, 235, 53, 0.5)",
     "race": "preta",
     "state": "RJ",
     "region": "Sudeste",
     "size": 0,
     "member": "no",
     "degrees": 1,
     "type": "federal",
     "ranking": 541
   },
   {
     "id": 150,
     "name": "Maria Aline Barros do Vale",
     "color": "rgba(245, 235, 53, 0.5)",
     "race": "parda",
     "state": "MG",
     "region": "Sudeste",
     "size": 1,
     "member": "no",
     "degrees": 0,
     "type": "federal",
     "ranking": 509
   },
   {
     "id": 151,
     "name": "Carla Aparecida Arena Ventura",
     "color": "rgba(0, 184, 104, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 9,
     "member": "no",
     "degrees": 16,
     "type": "estadual",
     "ranking": 592
   },
   {
     "id": 152,
     "name": "Viviane Coelho de Sellos-Knoerr",
     "color": "rgba(0, 184, 104, 0.5)",
     "race": "branca",
     "state": "PR",
     "region": "Sul",
     "size": 11,
     "member": "no",
     "degrees": 52,
     "type": "privada",
     "ranking": 486
   },
   {
     "id": 153,
     "name": "Rosana Aparecida Baeninger",
     "color": "rgba(0, 184, 104, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 3,
     "member": "no",
     "degrees": 5,
     "type": "estadual",
     "ranking": 449
   },
   {
     "id": 154,
     "name": "Mariângela Spotti Lopes Fujita",
     "color": "rgba(0, 184, 104, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 9,
     "member": "no",
     "degrees": 73,
     "type": "estadual",
     "ranking": 392
   },
   {
     "id": 155,
     "name": "Leilah Santiago Bufrem",
     "color": "rgba(0, 184, 104, 0.5)",
     "race": "branca",
     "state": "PE",
     "region": "Nordeste",
     "size": 13,
     "member": "no",
     "degrees": 40,
     "type": "estadual",
     "ranking": 367
   },
   {
     "id": 156,
     "name": "Maria Ines Souza Bravo",
     "color": "rgba(0, 184, 104, 0.5)",
     "race": "branca",
     "state": "RJ",
     "region": "Sudeste",
     "size": 9,
     "member": "no",
     "degrees": 39,
     "type": "privada",
     "ranking": 358
   },
   {
     "id": 157,
     "name": "Maria do Perpétuo Socorro Rodrigues Chaves",
     "color": "rgba(0, 184, 104, 0.5)",
     "race": "parda",
     "state": "AM",
     "region": "Norte",
     "size": 0,
     "member": "no",
     "degrees": 37,
     "type": "estadual",
     "ranking": 349
   },
   {
     "id": 158,
     "name": "Maria das Graças Targino",
     "color": "rgba(0, 184, 104, 0.5)",
     "race": "branca",
     "state": "PI",
     "region": "Nordeste",
     "size": 19,
     "member": "no",
     "degrees": 46,
     "type": "federal",
     "ranking": 337
   },
   {
     "id": 159,
     "name": "Maria Beatriz Costa Abramides",
     "color": "rgba(0, 184, 104, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 11,
     "member": "no",
     "degrees": 25,
     "type": "privada",
     "ranking": 326
   },
   {
     "id": 160,
     "name": "Marcia Caldas de Castro",
     "color": "rgba(0, 184, 104, 0.5)",
     "race": "branca",
     "state": "Boston",
     "region": "Exterior",
     "size": 12,
     "member": "no",
     "degrees": 11,
     "type": "exterior",
     "ranking": 309
   },
   {
     "id": 161,
     "name": "Maria de Fátima Ribeiro",
     "color": "rgba(0, 184, 104, 0.5)",
     "race": "branca",
     "state": "PR",
     "region": "Sul",
     "size": 2,
     "member": "no",
     "degrees": 17,
     "type": "privada",
     "ranking": 301
   },
   {
     "id": 162,
     "name": "Cicilia Maria Krohling Peruzzo",
     "color": "rgba(0, 184, 104, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 1,
     "member": "no",
     "degrees": 19,
     "type": "estadual",
     "ranking": 301
   },
   {
     "id": 163,
     "name": "Marcia Carla Pereira Ribeiro",
     "color": "rgba(0, 184, 104, 0.5)",
     "race": "branca",
     "state": "PR",
     "region": "Sul",
     "size": 13,
     "member": "no",
     "degrees": 31,
     "type": "federal",
     "ranking": 301
   },
   {
     "id": 164,
     "name": "Marta Lígia Pomim Valentim",
     "color": "rgba(0, 184, 104, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 12,
     "member": "no",
     "degrees": 28,
     "type": "estadual",
     "ranking": 300
   },
   {
     "id": 165,
     "name": "Gabrielle Bezerra Sales",
     "color": "rgba(0, 184, 104, 0.5)",
     "race": "branca",
     "state": "RS",
     "region": "Sul",
     "size": 4,
     "member": "no",
     "degrees": 3,
     "type": "exterior",
     "ranking": 299
   },
   {
     "id": 166,
     "name": "Tania Casado",
     "color": "rgba(0, 184, 104, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 0,
     "member": "no",
     "degrees": 38,
     "type": "estadual",
     "ranking": 297
   },
   {
     "id": 167,
     "name": "Vania Siciliano Aieta",
     "color": "rgba(0, 184, 104, 0.5)",
     "race": "branca",
     "state": "RJ",
     "region": "Sudeste",
     "size": 1,
     "member": "no",
     "degrees": 60,
     "type": "privada",
     "ranking": 295
   },
   {
     "id": 168,
     "name": "Elza Salvatori Berquó",
     "color": "rgba(0, 184, 104, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 7,
     "member": "yes",
     "degrees": 16,
     "type": "exterior",
     "ranking": 289
   },
   {
     "id": 169,
     "name": "Maria Cláudia da Silva Antunes de Souza",
     "color": "rgba(0, 184, 104, 0.5)",
     "race": "branca",
     "state": "SC",
     "region": "Sul",
     "size": 11,
     "member": "no",
     "degrees": 8,
     "type": "exterior",
     "ranking": 288
   },
   {
     "id": 170,
     "name": "Giselda Maria Fernandes Novaes Hironaka",
     "color": "rgba(0, 184, 104, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 4,
     "member": "no",
     "degrees": 15,
     "type": "estadual",
     "ranking": 286
   },
   {
     "id": 171,
     "name": "Sueli Mara Soares Pinto Ferreira",
     "color": "rgba(0, 184, 104, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 1,
     "member": "no",
     "degrees": 11,
     "type": "estadual",
     "ranking": 285
   },
   {
     "id": 172,
     "name": "Angela Maria Cavalcanti da Rocha",
     "color": "rgba(0, 184, 104, 0.5)",
     "race": "branca",
     "state": "RJ",
     "region": "Sudeste",
     "size": 4,
     "member": "no",
     "degrees": 19,
     "type": "exterior",
     "ranking": 283
   },
   {
     "id": 173,
     "name": "Sandra Regina Martini",
     "color": "rgba(0, 184, 104, 0.5)",
     "race": "branca",
     "state": "RS",
     "region": "Sul",
     "size": 7,
     "member": "no",
     "degrees": 2,
     "type": "exterior",
     "ranking": 278
   },
   {
     "id": 174,
     "name": "Beatriz Valadares Cendón",
     "color": "rgba(0, 184, 104, 0.5)",
     "race": "branca",
     "state": "MG",
     "region": "Sudeste",
     "size": 10,
     "member": "no",
     "degrees": 37,
     "type": "exterior",
     "ranking": 268
   },
   {
     "id": 175,
     "name": "Maria das Dores Saraiva de Loreto",
     "color": "rgba(0, 184, 104, 0.5)",
     "race": "branca",
     "state": "MG",
     "region": "Sudeste",
     "size": 0,
     "member": "no",
     "degrees": 7,
     "type": "federal",
     "ranking": 264
   },
   {
     "id": 176,
     "name": "Silvana Aparecida Borsetti Gregorio Vidotti",
     "color": "rgba(0, 184, 104, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 3,
     "member": "no",
     "degrees": 27,
     "type": "estadual",
     "ranking": 260
   },
   {
     "id": 177,
     "name": "Silvana Maria Escorsim",
     "color": "rgba(0, 184, 104, 0.5)",
     "race": "branca",
     "state": "PR",
     "region": "Sul",
     "size": 1,
     "member": "no",
     "degrees": 6,
     "type": "privada",
     "ranking": 259
   },
   {
     "id": 178,
     "name": "Aldaiza Sposati",
     "color": "rgba(0, 184, 104, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 25,
     "member": "no",
     "degrees": 13,
     "type": "privada",
     "ranking": 258
   },
   {
     "id": 179,
     "name": "Marlei Pozzebon",
     "color": "rgba(0, 184, 104, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 9,
     "member": "no",
     "degrees": 17,
     "type": "exterior",
     "ranking": 258
   },
   {
     "id": 180,
     "name": "Salete Oro Boff",
     "color": "rgba(0, 184, 104, 0.5)",
     "race": "branca",
     "state": "RS",
     "region": "Sul",
     "size": 17,
     "member": "no",
     "degrees": 3,
     "type": "privada",
     "ranking": 223
   },
   {
     "id": 181,
     "name": "Maria Sylvia Macchione Saes",
     "color": "rgba(0, 184, 104, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 0,
     "member": "no",
     "degrees": 16,
     "type": "estadual",
     "ranking": 250
   },
   {
     "id": 182,
     "name": "Plácida Leopoldina Ventura Amorim da Costa Santos",
     "color": "rgba(0, 184, 104, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 3,
     "member": "no",
     "degrees": 26,
     "type": "estadual",
     "ranking": 250
   },
   {
     "id": 183,
     "name": "Suzana Braga Rodrigues",
     "color": "rgba(0, 184, 104, 0.5)",
     "race": "branca",
     "state": "MG",
     "region": "Sudeste",
     "size": 2,
     "member": "no",
     "degrees": 27,
     "type": "exterior",
     "ranking": 246
   },
   {
     "id": 184,
     "name": "Maria Aparecida Gouvêa",
     "color": "rgba(0, 184, 104, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 1,
     "member": "no",
     "degrees": 87,
     "type": "estadual",
     "ranking": 246
   },
   {
     "id": 185,
     "name": "Maria Liduína de Oliveira e Silva",
     "color": "rgba(0, 184, 104, 0.5)",
     "race": "parda",
     "state": "SP",
     "region": "Sudeste",
     "size": 13,
     "member": "no",
     "degrees": 6,
     "type": "privada",
     "ranking": 243
   },
   {
     "id": 186,
     "name": "Renata Maria Abrantes Baracho Porto",
     "color": "rgba(0, 184, 104, 0.5)",
     "race": "branca",
     "state": "MG",
     "region": "Sudeste",
     "size": 2,
     "member": "no",
     "degrees": 12,
     "type": "federal",
     "ranking": 240
   },
   {
     "id": 187,
     "name": "Betina Treiger Grupenmacher",
     "color": "rgba(0, 184, 104, 0.5)",
     "race": "branca",
     "state": "PR",
     "region": "Sul",
     "size": 1,
     "member": "no",
     "degrees": 22,
     "type": "federal",
     "ranking": 240
   },
   {
     "id": 188,
     "name": "Mara Vidigal Darcanchy",
     "color": "rgba(0, 184, 104, 0.5)",
     "race": "branca",
     "state": "PR",
     "region": "Sul",
     "size": 2,
     "member": "no",
     "degrees": 34,
     "type": "privada",
     "ranking": 240
   },
   {
     "id": 189,
     "name": "Rosângela Angelin",
     "color": "rgba(0, 184, 104, 0.5)",
     "race": "branca",
     "state": "RS",
     "region": "Sul",
     "size": 1,
     "member": "no",
     "degrees": 0,
     "type": "exterior",
     "ranking": 236
   },
   {
     "id": 190,
     "name": "Larissa Liz Odreski Ramina",
     "color": "rgba(0, 184, 104, 0.5)",
     "race": "branca",
     "state": "PR",
     "region": "Sul",
     "size": 5,
     "member": "no",
     "degrees": 8,
     "type": "estadual",
     "ranking": 233
   },
   {
     "id": 191,
     "name": "Maria Immacolata Vassallo de Lopes",
     "color": "rgba(0, 184, 104, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 1,
     "member": "no",
     "degrees": 15,
     "type": "estadual",
     "ranking": 233
   },
   {
     "id": 192,
     "name": "Thaise Nara Graziottin Costa",
     "color": "rgba(0, 184, 104, 0.5)",
     "race": "branca",
     "state": "RS",
     "region": "Sul",
     "size": 3,
     "member": "no",
     "degrees": 15,
     "type": "privada",
     "ranking": 233
   },
   {
     "id": 193,
     "name": "Patrícia Krieger Grossi",
     "color": "rgba(0, 184, 104, 0.5)",
     "race": "branca",
     "state": "RS",
     "region": "Sul",
     "size": 4,
     "member": "no",
     "degrees": 48,
     "type": "exterior",
     "ranking": 233
   },
   {
     "id": 194,
     "name": "Maria Elizabeth Guimarães Teixeira Rocha",
     "color": "rgba(0, 184, 104, 0.5)",
     "race": "branca",
     "state": "DF",
     "region": "Centro-Oeste",
     "size": 1,
     "member": "no",
     "degrees": 97,
     "type": "federal",
     "ranking": 229
   },
   {
     "id": 195,
     "name": "Celia Ribeiro Zaher",
     "color": "rgba(0, 184, 104, 0.5)",
     "race": "branca",
     "state": "RJ",
     "region": "Sudeste",
     "size": 1,
     "member": "no",
     "degrees": 35,
     "type": "federal",
     "ranking": 228
   },
   {
     "id": 196,
     "name": "Cláudia Souza Passador",
     "color": "rgba(0, 184, 104, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 0,
     "member": "no",
     "degrees": 33,
     "type": "estadual",
     "ranking": 225
   },
   {
     "id": 197,
     "name": "Ana Valéria Machado Mendonça",
     "color": "rgba(0, 184, 104, 0.5)",
     "race": "branca",
     "state": "DF",
     "region": "Centro-Oeste",
     "size": 0,
     "member": "no",
     "degrees": 26,
     "type": "federal",
     "ranking": 223
   },
   {
     "id": 198,
     "name": "Eliana Mendes de Souza Teixeira Roque",
     "color": "rgba(0, 184, 104, 0.5)",
     "race": "parda",
     "state": "SP",
     "region": "Sudeste",
     "size": 10,
     "member": "no",
     "degrees": 8,
     "type": "estadual",
     "ranking": 205
   },
   {
     "id": 199,
     "name": "Maria Aparecida Moura",
     "color": "rgba(0, 184, 104, 0.5)",
     "race": "preta",
     "state": "MG",
     "region": "Sudeste",
     "size": 9,
     "member": "no",
     "degrees": 25,
     "type": "privada",
     "ranking": 197
   },
   {
     "id": 200,
     "name": "Silene de Moraes Freire",
     "color": "rgba(0, 184, 104, 0.5)",
     "race": "parda",
     "state": "RJ",
     "region": "Sudeste",
     "size": 2,
     "member": "no",
     "degrees": 12,
     "type": "estadual",
     "ranking": 191
   },
   {
     "id": 201,
     "name": "Bluma Guenther Soares",
     "color": "rgba(215, 64, 255, 0.5)",
     "race": "parda",
     "state": "RJ",
     "region": "Sudeste",
     "size": 68,
     "member": "no",
     "degrees": 4,
     "type": "federal",
     "ranking": 864
   },
   {
     "id": 202,
     "name": "Maria Ines Bruno Tavares",
     "color": "rgba(215, 64, 255, 0.5)",
     "race": "branca",
     "state": "RJ",
     "region": "Sudeste",
     "size": 76,
     "member": "no",
     "degrees": 23,
     "type": "federal",
     "ranking": 858
   },
   {
     "id": 203,
     "name": "Maria Regina Wolf Maciel",
     "color": "rgba(215, 64, 255, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 28,
     "member": "no",
     "degrees": 11,
     "type": "exterior",
     "ranking": 655
   },
   {
     "id": 204,
     "name": "Fernanda Margarida Barbosa Coutinho",
     "color": "rgba(215, 64, 255, 0.5)",
     "race": "branca",
     "state": "RJ",
     "region": "Sudeste",
     "size": 46,
     "member": "no",
     "degrees": 6,
     "type": "federal",
     "ranking": 574
   },
   {
     "id": 205,
     "name": "Iêda Maria Garcia dos Santos",
     "color": "rgba(215, 64, 255, 0.5)",
     "race": "branca",
     "state": "PB",
     "region": "Nordeste",
     "size": 4,
     "member": "no",
     "degrees": 9,
     "type": "federal",
     "ranking": 571
   },
   {
     "id": 206,
     "name": "Dulce Maria de Araújo Melo",
     "color": "rgba(215, 64, 255, 0.5)",
     "race": "parda",
     "state": "RN",
     "region": "Nordeste",
     "size": 34,
     "member": "no",
     "degrees": 5,
     "type": "estadual",
     "ranking": 555
   },
   {
     "id": 207,
     "name": "Maria Aparecida Zaghete Bertochi",
     "color": "rgba(215, 64, 255, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 3,
     "member": "no",
     "degrees": 4,
     "type": "federal",
     "ranking": 553
   },
   {
     "id": 208,
     "name": "Selene Maria de Arruda Guelli Ulson de Souza",
     "color": "rgba(215, 64, 255, 0.5)",
     "race": "branca",
     "state": "SC",
     "region": "Sul",
     "size": 10,
     "member": "no",
     "degrees": 34,
     "type": "federal",
     "ranking": 537
   },
   {
     "id": 209,
     "name": "Raquel Santos Mauler",
     "color": "rgba(215, 64, 255, 0.5)",
     "race": "branca",
     "state": "RS",
     "region": "Sul",
     "size": 5,
     "member": "no",
     "degrees": 0,
     "type": "federal",
     "ranking": 491
   },
   {
     "id": 210,
     "name": "Marisa Masumi Beppu",
     "color": "rgba(215, 64, 255, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 10,
     "member": "no",
     "degrees": 35,
     "type": "estadual",
     "ranking": 490
   },
   {
     "id": 211,
     "name": "Luciana Reyes Pires Kassab",
     "color": "rgba(215, 64, 255, 0.5)",
     "race": "parda",
     "state": "SP",
     "region": "Sudeste",
     "size": 32,
     "member": "no",
     "degrees": 10,
     "type": "estadual",
     "ranking": 465
   },
   {
     "id": 212,
     "name": "Ruth Herta Goldschmidt Aliaga Kiminami",
     "color": "rgba(215, 64, 255, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 1,
     "member": "no",
     "degrees": 12,
     "type": "exterior",
     "ranking": 456
   },
   {
     "id": 213,
     "name": "Ducinei Garcia",
     "color": "rgba(215, 64, 255, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 2,
     "member": "no",
     "degrees": 19,
     "type": "estadual",
     "ranking": 443
   },
   {
     "id": 214,
     "name": "Gisella Maria Zanin",
     "color": "rgba(215, 64, 255, 0.5)",
     "race": "branca",
     "state": "PR",
     "region": "Sul",
     "size": 7,
     "member": "no",
     "degrees": 25,
     "type": "estadual",
     "ranking": 439
   },
   {
     "id": 215,
     "name": "Linda Viola Ehlin Caldas",
     "color": "rgba(215, 64, 255, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 4,
     "member": "no",
     "degrees": 1,
     "type": "estadual",
     "ranking": 438
   },
   {
     "id": 216,
     "name": "Andrea Simone Stucchi de Camargo Alvarez Bernardez",
     "color": "rgba(215, 64, 255, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 17,
     "member": "no",
     "degrees": 7,
     "type": "estadual",
     "ranking": 431
   },
   {
     "id": 217,
     "name": "Rosangela Bergamasco",
     "color": "rgba(215, 64, 255, 0.5)",
     "race": "branca",
     "state": "PR",
     "region": "Sul",
     "size": 6,
     "member": "no",
     "degrees": 9,
     "type": "exterior",
     "ranking": 430
   },
   {
     "id": 218,
     "name": "Sofia Maria Carrato Diniz",
     "color": "rgba(215, 64, 255, 0.5)",
     "race": "branca",
     "state": "MG",
     "region": "Sudeste",
     "size": 4,
     "member": "no",
     "degrees": 75,
     "type": "exterior",
     "ranking": 420
   },
   {
     "id": 219,
     "name": "Raquel de Lima Camargo Giordano",
     "color": "rgba(215, 64, 255, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 4,
     "member": "no",
     "degrees": 10,
     "type": "estadual",
     "ranking": 419
   },
   {
     "id": 220,
     "name": "Judith Pessoa de Andrade Feitosa",
     "color": "rgba(215, 64, 255, 0.5)",
     "race": "branca",
     "state": "CE",
     "region": "Nordeste",
     "size": 10,
     "member": "no",
     "degrees": 3,
     "type": "estadual",
     "ranking": 418
   },
   {
     "id": 221,
     "name": "Maria do Carmo Rangel Santos Varela",
     "color": "rgba(215, 64, 255, 0.5)",
     "race": "branca",
     "state": "RS",
     "region": "Sul",
     "size": 32,
     "member": "no",
     "degrees": 4,
     "type": "estadual",
     "ranking": 416
   },
   {
     "id": 222,
     "name": "Andrea Moura Bernardes",
     "color": "rgba(215, 64, 255, 0.5)",
     "race": "branca",
     "state": "RS",
     "region": "Sul",
     "size": 8,
     "member": "no",
     "degrees": 18,
     "type": "exterior",
     "ranking": 410
   },
   {
     "id": 223,
     "name": "Martha Simões Ribeiro",
     "color": "rgba(215, 64, 255, 0.5)",
     "race": "parda",
     "state": "SP",
     "region": "Sudeste",
     "size": 3,
     "member": "no",
     "degrees": 29,
     "type": "estadual",
     "ranking": 408
   },
   {
     "id": 224,
     "name": "Regina de Fátima Peralta Muniz Moreira",
     "color": "rgba(215, 64, 255, 0.5)",
     "race": "branca",
     "state": "SC",
     "region": "Sul",
     "size": 11,
     "member": "no",
     "degrees": 20,
     "type": "federal",
     "ranking": 400
   },
   {
     "id": 225,
     "name": "Diana Cristina Silva de Azevedo",
     "color": "rgba(215, 64, 255, 0.5)",
     "race": "branca",
     "state": "CE",
     "region": "Nordeste",
     "size": 8,
     "member": "no",
     "degrees": 4,
     "type": "exterior",
     "ranking": 398
   },
   {
     "id": 226,
     "name": "Eliana Navarro dos Santos Muccillo",
     "color": "rgba(215, 64, 255, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 33,
     "member": "no",
     "degrees": 4,
     "type": "estadual",
     "ranking": 398
   },
   {
     "id": 227,
     "name": "Claudia Sayer",
     "color": "rgba(215, 64, 255, 0.5)",
     "race": "branca",
     "state": "SC",
     "region": "Sul",
     "size": 6,
     "member": "no",
     "degrees": 3,
     "type": "federal",
     "ranking": 395
   },
   {
     "id": 228,
     "name": "Mirabel Cerqueira Rezende",
     "color": "rgba(215, 64, 255, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 16,
     "member": "no",
     "degrees": 10,
     "type": "estadual",
     "ranking": 385
   },
   {
     "id": 229,
     "name": "Maria Bernadete Amâncio Varesche",
     "color": "rgba(215, 64, 255, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 0,
     "member": "no",
     "degrees": 11,
     "type": "estadual",
     "ranking": 377
   },
   {
     "id": 230,
     "name": "Vanessa de Freitas Cunha Lins",
     "color": "rgba(215, 64, 255, 0.5)",
     "race": "branca",
     "state": "MG",
     "region": "Sudeste",
     "size": 9,
     "member": "no",
     "degrees": 37,
     "type": "federal",
     "ranking": 303
   },
   {
     "id": 231,
     "name": "Marcia Walquiria de Carvalho Dezotti",
     "color": "rgba(215, 64, 255, 0.5)",
     "race": "branca",
     "state": "RJ",
     "region": "Sudeste",
     "size": 3,
     "member": "no",
     "degrees": 23,
     "type": "estadual",
     "ranking": 373
   },
   {
     "id": 232,
     "name": "Elisabete Frollini",
     "color": "rgba(215, 64, 255, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 8,
     "member": "no",
     "degrees": 3,
     "type": "estadual",
     "ranking": 367
   },
   {
     "id": 233,
     "name": "Maria Ines Basso Bernardi",
     "color": "rgba(215, 64, 255, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 32,
     "member": "no",
     "degrees": 7,
     "type": "federal",
     "ranking": 367
   },
   {
     "id": 234,
     "name": "Debora Terezia Balogh",
     "color": "rgba(215, 64, 255, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 5,
     "member": "no",
     "degrees": 0,
     "type": "estadual",
     "ranking": 363
   },
   {
     "id": 235,
     "name": "Luciana Rocha Barros Gonçalves",
     "color": "rgba(215, 64, 255, 0.5)",
     "race": "branca",
     "state": "CE",
     "region": "Nordeste",
     "size": 7,
     "member": "no",
     "degrees": 6,
     "type": "federal",
     "ranking": 361
   },
   {
     "id": 236,
     "name": "Virginia Sampaio Teixeira Ciminelli",
     "color": "rgba(215, 64, 255, 0.5)",
     "race": "branca",
     "state": "MG",
     "region": "Sudeste",
     "size": 12,
     "member": "yes",
     "degrees": 25,
     "type": "exterior",
     "ranking": 357
   },
   {
     "id": 237,
     "name": "Fernanda Roberta Marciano",
     "color": "rgba(215, 64, 255, 0.5)",
     "race": "branca",
     "state": "PI",
     "region": "Nordeste",
     "size": 14,
     "member": "no",
     "degrees": 9,
     "type": "federal",
     "ranking": 354
   },
   {
     "id": 238,
     "name": "Helen Jamil Khoury",
     "color": "rgba(215, 64, 255, 0.5)",
     "race": "branca",
     "state": "PE",
     "region": "Nordeste",
     "size": 7,
     "member": "no",
     "degrees": 12,
     "type": "privada",
     "ranking": 353
   },
   {
     "id": 239,
     "name": "Cleide Mara Faria Soares",
     "color": "rgba(215, 64, 255, 0.5)",
     "race": "branca",
     "state": "SE",
     "region": "Nordeste",
     "size": 11,
     "member": "no",
     "degrees": 0,
     "type": "estadual",
     "ranking": 345
   },
   {
     "id": 240,
     "name": "Cheila Gonçalves Mothé",
     "color": "rgba(215, 64, 255, 0.5)",
     "race": "preta",
     "state": "RJ",
     "region": "Sudeste",
     "size": 37,
     "member": "no",
     "degrees": 22,
     "type": "estadual",
     "ranking": 344
   },
   {
     "id": 241,
     "name": "Leda dos Reis Castilho",
     "color": "rgba(215, 64, 255, 0.5)",
     "race": "branca",
     "state": "RJ",
     "region": "Sudeste",
     "size": 10,
     "member": "no",
     "degrees": 40,
     "type": "exterior",
     "ranking": 330
   },
   {
     "id": 242,
     "name": "Sergiane Caldas Barbosa",
     "color": "rgba(215, 64, 255, 0.5)",
     "race": "branca",
     "state": "RS",
     "region": "Sul",
     "size": 10,
     "member": "no",
     "degrees": 11,
     "type": "federal",
     "ranking": 329
   },
   {
     "id": 243,
     "name": "Alexandra Ancelmo Piscitelli Mansur",
     "color": "rgba(215, 64, 255, 0.5)",
     "race": "branca",
     "state": "MG",
     "region": "Sudeste",
     "size": 18,
     "member": "no",
     "degrees": 4,
     "type": "federal",
     "ranking": 323
   },
   {
     "id": 244,
     "name": "Irenilza de Alencar Naas",
     "color": "rgba(215, 64, 255, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 2,
     "member": "no",
     "degrees": 39,
     "type": "exterior",
     "ranking": 318
   },
   {
     "id": 245,
     "name": "Mariana de Mattos Vieira Mello Souza",
     "color": "rgba(215, 64, 255, 0.5)",
     "race": "branca",
     "state": "RJ",
     "region": "Sudeste",
     "size": 9,
     "member": "no",
     "degrees": 12,
     "type": "federal",
     "ranking": 312
   },
   {
     "id": 246,
     "name": "Ana Paula da Luz",
     "color": "rgba(215, 64, 255, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 28,
     "member": "no",
     "degrees": 5,
     "type": "federal",
     "ranking": 309
   },
   {
     "id": 247,
     "name": "Ligia Damasceno Ferreira Marczak",
     "color": "rgba(215, 64, 255, 0.5)",
     "race": "branca",
     "state": "RS",
     "region": "Sul",
     "size": 0,
     "member": "no",
     "degrees": 34,
     "type": "federal",
     "ranking": 308
   },
   {
     "id": 248,
     "name": "Maria Helena Andrade Santana",
     "color": "rgba(215, 64, 255, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 7,
     "member": "no",
     "degrees": 8,
     "type": "estadual",
     "ranking": 307
   },
   {
     "id": 249,
     "name": "Telma Teixeira Franco",
     "color": "rgba(215, 64, 255, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 11,
     "member": "no",
     "degrees": 5,
     "type": "exterior",
     "ranking": 305
   },
   {
     "id": 250,
     "name": "Neyde Yukie Murakami Iha",
     "color": "rgba(215, 64, 255, 0.5)",
     "race": "branca",
     "state": "SP",
     "region": "Sudeste",
     "size": 12,
     "member": "no",
     "degrees": 12,
     "type": "estadual",
     "ranking": 305
   }
  ],
};
